// Auto-generated by build.js
// 微信小游戏版本 - 打包时间: 2026-04-15T07:10:26.521Z

const __modules = {};

// Module: src\math.js
__modules[2] = (function() {
  const module = { exports: {} };
  /**
   * math.js - 向量与矩阵工具库
   * 提供3D游戏所需的基础数学运算，纯JS实现，无外部依赖
   */
  
  // ===================== Vec3 三维向量 =====================
  
  class Vec3 {
    constructor(x = 0, y = 0, z = 0) {
      this.x = x;
      this.y = y;
      this.z = z;
    }
  
    clone() {
      return new Vec3(this.x, this.y, this.z);
    }
  
    set(x, y, z) {
      this.x = x; this.y = y; this.z = z;
      return this;
    }
  
    add(v) {
      return new Vec3(this.x + v.x, this.y + v.y, this.z + v.z);
    }
  
    sub(v) {
      return new Vec3(this.x - v.x, this.y - v.y, this.z - v.z);
    }
  
    scale(s) {
      return new Vec3(this.x * s, this.y * s, this.z * s);
    }
  
    length() {
      return Math.sqrt(this.x * this.x + this.y * this.y + this.z * this.z);
    }
  
    normalize() {
      const len = this.length();
      return len > 0 ? this.scale(1 / len) : new Vec3();
    }
  
    dot(v) {
      return this.x * v.x + this.y * v.y + this.z * v.z;
    }
  
    cross(v) {
      return new Vec3(
        this.y * v.z - this.z * v.y,
        this.z * v.x - this.x * v.z,
        this.x * v.y - this.y * v.x
      );
    }
  }
  
  // ===================== Mat4 4x4矩阵（列主序） =====================
  
  class Mat4 {
    constructor() {
      // 16个元素，列主序存储，初始为单位矩阵
      this.m = new Float32Array([
        1, 0, 0, 0,
        0, 1, 0, 0,
        0, 0, 1, 0,
        0, 0, 0, 1
      ]);
    }
  
    /** 单位矩阵 */
    static identity() {
      return new Mat4();
    }
  
    /** 透视投影矩阵 */
    static perspective(fov, aspect, near, far) {
      const f = 1.0 / Math.tan(fov / 2);
      const nf = 1 / (near - far);
      const out = new Mat4();
      out.m[0] = f / aspect;
      out.m[5] = f;
      out.m[10] = (far + near) * nf;
      out.m[11] = -1;
      out.m[14] = 2 * far * near * nf;
      out.m[15] = 0;
      return out;
    }
  
    /** 视图矩阵（lookAt） */
    static lookAt(eye, center, up) {
      const z = eye.sub(center).normalize();
      const x = up.cross(z).normalize();
      const y = z.cross(x).normalize();
  
      const out = new Mat4();
      out.m[0] = x.x; out.m[1] = y.x; out.m[2] = z.x; out.m[3] = 0;
      out.m[4] = x.y; out.m[5] = y.y; out.m[6] = z.y; out.m[7] = 0;
      out.m[8] = x.z; out.m[9] = y.z; out.m[10] = z.z; out.m[11] = 0;
      out.m[12] = -x.dot(eye);
      out.m[13] = -y.dot(eye);
      out.m[14] = -z.dot(eye);
      out.m[15] = 1;
      return out;
    }
  
    /** 矩阵乘法 this × other */
    multiply(other) {
      const a = this.m, b = other.m;
      const out = new Mat4();
      const o = out.m;
      for (let i = 0; i < 4; i++) {
        for (let j = 0; j < 4; j++) {
          o[j * 4 + i] =
            a[i] * b[j * 4] +
            a[4 + i] * b[j * 4 + 1] +
            a[8 + i] * b[j * 4 + 2] +
            a[12 + i] * b[j * 4 + 3];
        }
      }
      return out;
    }
  }
  
  module.exports.Vec3 = Vec3;
  module.exports.Mat4 = Mat4;;
  
  return module.exports;
})();

// Module: src\blocks.js
__modules[5] = (function() {
  const module = { exports: {} };
  /**
   * blocks.js - 方块类型定义
   * 每种方块有 id、name、颜色（用于纹理着色）、是否透明、是否固体
   */
  
  class BlockType {
    /**
     * @param {number} id
     * @param {string} name
     * @param {number[]} color - [r, g, b] 范围 0-1
     * @param {boolean} transparent
     * @param {boolean} solid
     */
    constructor(id, name, color, transparent = false, solid = true) {
      this.id = id;
      this.name = name;
      this.color = color;
      this.transparent = transparent;
      this.solid = solid;
    }
  }
  
  /** 方块注册表 */
  class BlockRegistry {
    constructor() {
      this._blocks = new Map();
      this._nextId = 0;
    }
  
    /** 注册一个方块类型 */
    register(name, color, transparent = false, solid = true) {
      const id = this._nextId++;
      const block = new BlockType(id, name, color, transparent, solid);
      this._blocks.set(id, block);
      this[name.toUpperCase()] = id; // 便捷常量 BlockRegistry.GRASS 等
      return id;
    }
  
    /** 通过 id 获取方块类型 */
    get(id) {
      return this._blocks.get(id);
    }
  
    /** 是否为空气/空方块 */
    isAir(id) {
      return id === 0;
    }
  }
  
  // 创建全局注册表并注册所有方块
  const Blocks = new BlockRegistry();
  
  // id=0 预留给空气
  Blocks._nextId = 1;
  Blocks.AIR = 0;
  
  Blocks.register('GRASS',    [0.36, 0.68, 0.24]);
  Blocks.register('DIRT',     [0.55, 0.37, 0.24]);
  Blocks.register('STONE',    [0.50, 0.50, 0.50]);
  Blocks.register('SAND',     [0.86, 0.82, 0.62]);
  Blocks.register('WATER',    [0.20, 0.40, 0.80], true, false);
  Blocks.register('WOOD',     [0.55, 0.35, 0.16]);
  Blocks.register('LEAVES',   [0.20, 0.55, 0.15], true);
  Blocks.register('BEDROCK',  [0.22, 0.22, 0.22]);
  Blocks.register('SNOW',     [0.95, 0.95, 0.98]);
  Blocks.register('COAL_ORE', [0.30, 0.30, 0.30]);
  Blocks.register('IRON_ORE', [0.60, 0.50, 0.40]);
  
  module.exports.Blocks = Blocks;
  module.exports.BlockType = BlockType;
  module.exports.BlockRegistry = BlockRegistry;;
  
  return module.exports;
})();

// Module: src\chunk.js
__modules[4] = (function() {
  const module = { exports: {} };
  /**
   * chunk.js - 区块数据与网格构建
   * 一个 Chunk 是 16×64×16 的方块区域
   * 负责存储方块数据并生成渲染用的顶点/索引数据
   */
  
  const { Blocks } = __modules[5];
  
  const CHUNK_WIDTH = 16;   // X 方向
  const CHUNK_HEIGHT = 64;  // Y 方向（高度）
  const CHUNK_DEPTH = 16;   // Z 方向
  
  /** 6个面的顶点偏移与法线方向 */
  const FACE_DEFS = [
    { dir: [0, 1, 0],  corners: [[0,1,1],[1,1,1],[1,1,0],[0,1,0]] },   // 顶面 +Y
    { dir: [0, -1, 0], corners: [[0,0,0],[1,0,0],[1,0,1],[0,0,1]] },   // 底面 -Y
    { dir: [1, 0, 0],  corners: [[1,0,0],[1,1,0],[1,1,1],[1,0,1]] },   // 右面 +X
    { dir: [-1, 0, 0], corners: [[0,0,1],[0,1,1],[0,1,0],[0,0,0]] },   // 左面 -X
    { dir: [0, 0, 1],  corners: [[0,0,1],[1,0,1],[1,1,1],[0,1,1]] },   // 前面 +Z
    { dir: [0, 0, -1], corners: [[1,0,0],[0,0,0],[0,1,0],[1,1,0]] },   // 后面 -Z
  ];
  
  class Chunk {
    /**
     * @param {number} cx - 区块 X 坐标
     * @param {number} cz - 区块 Z 坐标
     */
    constructor(cx, cz) {
      this.cx = cx;
      this.cz = cz;
      // 一维数组存储方块 id
      this.blocks = new Uint8Array(CHUNK_WIDTH * CHUNK_HEIGHT * CHUNK_DEPTH);
      // 渲染网格数据（由 buildMesh 生成）
      this.mesh = null;
      this.dirty = true;
    }
  
    // ---- 方块读写 ----
  
    _index(x, y, z) {
      return y * CHUNK_WIDTH * CHUNK_DEPTH + z * CHUNK_WIDTH + x;
    }
  
    getBlock(x, y, z) {
      if (x < 0 || x >= CHUNK_WIDTH || y < 0 || y >= CHUNK_HEIGHT || z < 0 || z >= CHUNK_DEPTH) {
        return 0; // 越界当空气
      }
      return this.blocks[this._index(x, y, z)];
    }
  
    setBlock(x, y, z, blockId) {
      if (x < 0 || x >= CHUNK_WIDTH || y < 0 || y >= CHUNK_HEIGHT || z < 0 || z >= CHUNK_DEPTH) return;
      this.blocks[this._index(x, y, z)] = blockId;
      this.dirty = true;
    }
  
    // ---- 网格构建 ----
  
    /**
     * 构建渲染网格
     * @param {Function} getWorldBlock - (wx, wy, wz) => blockId 获取世界方块
     * @returns {{ solidMesh: object, waterMesh: object }}
     */
    buildMesh(getWorldBlock) {
      const solidPos = [], solidNorm = [], solidCol = [], solidIdx = [];
      const waterPos = [], waterNorm = [], waterCol = [], waterIdx = [];
  
      const ox = this.cx * CHUNK_WIDTH;
      const oz = this.cz * CHUNK_DEPTH;
  
      for (let y = 0; y < CHUNK_HEIGHT; y++) {
        for (let z = 0; z < CHUNK_DEPTH; z++) {
          for (let x = 0; x < CHUNK_WIDTH; x++) {
            const blockId = this.getBlock(x, y, z);
            if (blockId === 0) continue; // 空气不渲染
  
            const blockType = Blocks.get(blockId);
            if (!blockType) continue;
  
            const isWater = blockId === Blocks.WATER;
            const positions = isWater ? waterPos : solidPos;
            const normals = isWater ? waterNorm : solidNorm;
            const colors = isWater ? waterCol : solidCol;
            const indices = isWater ? waterIdx : solidIdx;
  
            for (let f = 0; f < 6; f++) {
              const face = FACE_DEFS[f];
              // 相邻方块的世界坐标
              const nx = x + face.dir[0];
              const ny = y + face.dir[1];
              const nz = z + face.dir[2];
  
              // 获取相邻方块（可能跨 Chunk）
              let neighborId;
              if (nx >= 0 && nx < CHUNK_WIDTH && nz >= 0 && nz < CHUNK_DEPTH && ny >= 0 && ny < CHUNK_HEIGHT) {
                neighborId = this.getBlock(nx, ny, nz);
              } else if (ny < 0 || ny >= CHUNK_HEIGHT) {
                neighborId = 0;
              } else {
                neighborId = getWorldBlock(ox + nx, ny, oz + nz);
              }
  
              // 相邻方块为空气或透明时才绘制此面
              // 但是如果是水面，相邻的也是水面，则不绘制内部面
              const neighborType = Blocks.get(neighborId);
              if (neighborId !== 0 && neighborType) {
                if (isWater && neighborId === Blocks.WATER) {
                  // 水与水相邻，不绘制面
                  continue;
                } else if (!neighborType.transparent) {
                  continue;
                }
              }
  
              const vertCount = positions.length / 3;
              const cr = blockType.color[0];
              const cg = blockType.color[1];
              const cb = blockType.color[2];
  
              for (const corner of face.corners) {
                positions.push(ox + x + corner[0], y + corner[1], oz + z + corner[2]);
                normals.push(face.dir[0], face.dir[1], face.dir[2]);
                colors.push(cr, cg, cb);
              }
  
              indices.push(
                vertCount, vertCount + 1, vertCount + 2,
                vertCount, vertCount + 2, vertCount + 3
              );
            }
          }
        }
      }
  
      this.mesh = {
        solidMesh: {
          positions: new Float32Array(solidPos),
          normals: new Float32Array(solidNorm),
          colors: new Float32Array(solidCol),
          indices: new Uint32Array(solidIdx),
        },
        waterMesh: {
          positions: new Float32Array(waterPos),
          normals: new Float32Array(waterNorm),
          colors: new Float32Array(waterCol),
          indices: new Uint32Array(waterIdx),
        }
      };
      this.dirty = false;
      return this.mesh;
    }
  }
  
  // 导出常量供外部使用
  Chunk.WIDTH = CHUNK_WIDTH;
  Chunk.HEIGHT = CHUNK_HEIGHT;
  Chunk.DEPTH = CHUNK_DEPTH;
  
  module.exports.Chunk = Chunk;
  module.exports.CHUNK_WIDTH = CHUNK_WIDTH;
  module.exports.CHUNK_HEIGHT = CHUNK_HEIGHT;
  module.exports.CHUNK_DEPTH = CHUNK_DEPTH;;
  
  return module.exports;
})();

// Module: src\noise.js
__modules[6] = (function() {
  const module = { exports: {} };
  /**
   * noise.js - Simplex Noise 2D 噪声生成器
   * 用于程序化地形高度图生成
   * 基于 Stefan Gustavson 的简化噪声算法
   */
  
  class SimplexNoise {
    constructor(seed = 0) {
      this.grad3 = [
        [1,1,0],[-1,1,0],[1,-1,0],[-1,-1,0],
        [1,0,1],[-1,0,1],[1,0,-1],[-1,0,-1],
        [0,1,1],[0,-1,1],[0,1,-1],[0,-1,-1]
      ];
      this.perm = new Uint8Array(512);
      this._initPerm(seed);
    }
  
    /** 基于种子的排列表初始化 */
    _initPerm(seed) {
      const p = new Uint8Array(256);
      for (let i = 0; i < 256; i++) p[i] = i;
      // Fisher-Yates 洗牌，使用种子生成伪随机序列
      let s = seed;
      for (let i = 255; i > 0; i--) {
        s = (s * 16807 + 0) % 2147483647;
        const j = s % (i + 1);
        [p[i], p[j]] = [p[j], p[i]];
      }
      for (let i = 0; i < 512; i++) {
        this.perm[i] = p[i & 255];
      }
    }
  
    /** 2D Simplex 噪声，返回值范围约 [-1, 1] */
    noise2D(xin, yin) {
      const F2 = 0.5 * (Math.sqrt(3.0) - 1.0);
      const G2 = (3.0 - Math.sqrt(3.0)) / 6.0;
  
      const s = (xin + yin) * F2;
      const i = Math.floor(xin + s);
      const j = Math.floor(yin + s);
      const t = (i + j) * G2;
      const X0 = i - t;
      const Y0 = j - t;
      const x0 = xin - X0;
      const y0 = yin - Y0;
  
      let i1, j1;
      if (x0 > y0) { i1 = 1; j1 = 0; }
      else { i1 = 0; j1 = 1; }
  
      const x1 = x0 - i1 + G2;
      const y1 = y0 - j1 + G2;
      const x2 = x0 - 1.0 + 2.0 * G2;
      const y2 = y0 - 1.0 + 2.0 * G2;
  
      const ii = i & 255;
      const jj = j & 255;
  
      const dot = (g, x, y) => g[0] * x + g[1] * y;
  
      let n0 = 0, n1 = 0, n2 = 0;
  
      let t0 = 0.5 - x0 * x0 - y0 * y0;
      if (t0 >= 0) {
        t0 *= t0;
        const gi0 = this.perm[ii + this.perm[jj]] % 12;
        n0 = t0 * t0 * dot(this.grad3[gi0], x0, y0);
      }
  
      let t1 = 0.5 - x1 * x1 - y1 * y1;
      if (t1 >= 0) {
        t1 *= t1;
        const gi1 = this.perm[ii + i1 + this.perm[jj + j1]] % 12;
        n1 = t1 * t1 * dot(this.grad3[gi1], x1, y1);
      }
  
      let t2 = 0.5 - x2 * x2 - y2 * y2;
      if (t2 >= 0) {
        t2 *= t2;
        const gi2 = this.perm[ii + 1 + this.perm[jj + 1]] % 12;
        n2 = t2 * t2 * dot(this.grad3[gi2], x2, y2);
      }
  
      return 70.0 * (n0 + n1 + n2);
    }
  
    /** 分形布朗运动（多层噪声叠加） */
    fbm(x, y, octaves = 4, lacunarity = 2.0, gain = 0.5) {
      let sum = 0;
      let amp = 1;
      let freq = 1;
      let maxAmp = 0;
      for (let i = 0; i < octaves; i++) {
        sum += this.noise2D(x * freq, y * freq) * amp;
        maxAmp += amp;
        amp *= gain;
        freq *= lacunarity;
      }
      return sum / maxAmp;
    }
  }
  
  module.exports.SimplexNoise = SimplexNoise;;
  
  return module.exports;
})();

// Module: src\world.js
__modules[3] = (function() {
  const module = { exports: {} };
  /**
   * world.js - 世界管理与地形生成
   * 管理多个 Chunk，提供方块的全局读写接口
   * 使用 Simplex Noise 生成程序化地形
   */
  
  const { Chunk, CHUNK_WIDTH, CHUNK_HEIGHT, CHUNK_DEPTH } = __modules[4];
  const { Blocks } = __modules[5];
  const { SimplexNoise } = __modules[6];
  
  /** 地形生成参数 */
  const TERRAIN_SEA_LEVEL = 20;
  const TERRAIN_SCALE = 0.02;     // 噪声缩放
  const TERRAIN_HEIGHT = 20;      // 地形振幅
  const TERRAIN_OCTAVES = 4;
  
  class World {
    constructor(seed = 42) {
      this.chunks = new Map();  // key: "cx,cz"
      this.noise = new SimplexNoise(seed);
      this.seed = seed;
      this.renderDistance = 4;  // 渲染半径（区块数）
    }
  
    _key(cx, cz) {
      return `${cx},${cz}`;
    }
  
    /** 获取或创建 Chunk */
    getChunk(cx, cz) {
      const key = this._key(cx, cz);
      if (!this.chunks.has(key)) {
        const chunk = new Chunk(cx, cz);
        this._generateTerrain(chunk);
        this.chunks.set(key, chunk);
      }
      return this.chunks.get(key);
    }
  
    /** 通过世界坐标获取方块 id */
    getBlock(wx, wy, wz) {
      const cx = Math.floor(wx / CHUNK_WIDTH);
      const cz = Math.floor(wz / CHUNK_DEPTH);
      const lx = ((wx % CHUNK_WIDTH) + CHUNK_WIDTH) % CHUNK_WIDTH;
      const lz = ((wz % CHUNK_DEPTH) + CHUNK_DEPTH) % CHUNK_DEPTH;
      const chunk = this.chunks.get(this._key(cx, cz));
      if (!chunk) return 0;
      return chunk.getBlock(lx, wy, lz);
    }
  
    /** 通过世界坐标设置方块 */
    setBlock(wx, wy, wz, blockId) {
      const cx = Math.floor(wx / CHUNK_WIDTH);
      const cz = Math.floor(wz / CHUNK_DEPTH);
      const lx = ((wx % CHUNK_WIDTH) + CHUNK_WIDTH) % CHUNK_WIDTH;
      const lz = ((wz % CHUNK_DEPTH) + CHUNK_DEPTH) % CHUNK_DEPTH;
      const chunk = this.getChunk(cx, cz);
      chunk.setBlock(lx, wy, lz, blockId);
      // 如果修改的是区块边界方块，需标记相邻区块为脏
      if (lx === 0) this._markDirty(cx - 1, cz);
      if (lx === CHUNK_WIDTH - 1) this._markDirty(cx + 1, cz);
      if (lz === 0) this._markDirty(cx, cz - 1);
      if (lz === CHUNK_DEPTH - 1) this._markDirty(cx, cz + 1);
    }
  
    _markDirty(cx, cz) {
      const chunk = this.chunks.get(this._key(cx, cz));
      if (chunk) chunk.dirty = true;
    }
  
    // ---- 地形生成 ----
  
    /** 为单个 Chunk 生成地形 */
    _generateTerrain(chunk) {
      const ox = chunk.cx * CHUNK_WIDTH;
      const oz = chunk.cz * CHUNK_DEPTH;
  
      for (let z = 0; z < CHUNK_DEPTH; z++) {
        for (let x = 0; x < CHUNK_WIDTH; x++) {
          const wx = ox + x;
          const wz = oz + z;
  
          // 用分形噪声生成高度
          const n = this.noise.fbm(wx * TERRAIN_SCALE, wz * TERRAIN_SCALE, TERRAIN_OCTAVES);
          const height = Math.floor(TERRAIN_SEA_LEVEL + n * TERRAIN_HEIGHT);
          const clampedHeight = Math.max(1, Math.min(CHUNK_HEIGHT - 1, height));
  
          for (let y = 0; y < CHUNK_HEIGHT; y++) {
            let blockId = 0; // 空气
  
            if (y === 0) {
              blockId = Blocks.BEDROCK;
            } else if (y < clampedHeight - 4) {
              blockId = Blocks.STONE;
            } else if (y < clampedHeight - 1) {
              blockId = Blocks.DIRT;
            } else if (y === clampedHeight - 1) {
              if (clampedHeight < TERRAIN_SEA_LEVEL - 1) {
                blockId = Blocks.SAND;
              } else if (clampedHeight > TERRAIN_SEA_LEVEL + 8) {
                blockId = Blocks.SNOW;
              } else {
                blockId = Blocks.GRASS;
              }
            } else if (y < TERRAIN_SEA_LEVEL && y >= clampedHeight) {
              blockId = Blocks.WATER;
            }
  
            chunk.setBlock(x, y, z, blockId);
          }
  
          // 简单的树木生成
          if (clampedHeight >= TERRAIN_SEA_LEVEL && clampedHeight < TERRAIN_SEA_LEVEL + 7) {
            const treeNoise = this.noise.noise2D(wx * 0.5, wz * 0.5);
            if (treeNoise > 0.7 && x > 2 && x < CHUNK_WIDTH - 2 && z > 2 && z < CHUNK_DEPTH - 2) {
              this._placeTree(chunk, x, clampedHeight, z);
            }
          }
        }
      }
      chunk.dirty = true;
    }
  
    /** 在指定位置放置一棵树 */
    _placeTree(chunk, x, baseY, z) {
      const trunkHeight = 4 + Math.floor(Math.abs(this.noise.noise2D(x, z)) * 2);
      // 树干
      for (let y = 0; y < trunkHeight; y++) {
        chunk.setBlock(x, baseY + y, z, Blocks.WOOD);
      }
      // 树冠
      const leafStart = baseY + trunkHeight - 1;
      for (let dy = 0; dy < 3; dy++) {
        const radius = dy === 2 ? 1 : 2;
        for (let dx = -radius; dx <= radius; dx++) {
          for (let dz = -radius; dz <= radius; dz++) {
            if (dx === 0 && dz === 0 && dy < 2) continue; // 树干位置不放叶子
            if (Math.abs(dx) === radius && Math.abs(dz) === radius && dy < 2) continue; // 去角
            chunk.setBlock(x + dx, leafStart + dy, z + dz, Blocks.LEAVES);
          }
        }
      }
    }
  
    /** 确保玩家周围的区块已加载 */
    ensureChunksAround(playerX, playerZ) {
      const pcx = Math.floor(playerX / CHUNK_WIDTH);
      const pcz = Math.floor(playerZ / CHUNK_DEPTH);
      for (let dx = -this.renderDistance; dx <= this.renderDistance; dx++) {
        for (let dz = -this.renderDistance; dz <= this.renderDistance; dz++) {
          this.getChunk(pcx + dx, pcz + dz);
        }
      }
    }
  
    /** 获取所有需要重建网格的 Chunk */
    getDirtyChunks() {
      const result = [];
      for (const chunk of this.chunks.values()) {
        if (chunk.dirty) result.push(chunk);
      }
      return result;
    }
  
    /** 获取指定坐标处的地形高度 */
    getHeight(wx, wz) {
      const n = this.noise.fbm(wx * TERRAIN_SCALE, wz * TERRAIN_SCALE, TERRAIN_OCTAVES);
      return Math.max(1, Math.min(CHUNK_HEIGHT - 1, Math.floor(TERRAIN_SEA_LEVEL + n * TERRAIN_HEIGHT)));
    }
  }
  
  module.exports.World = World;;
  
  return module.exports;
})();

// Module: src\shaders.js
__modules[8] = (function() {
  const module = { exports: {} };
  /**
   * shaders.js - WebGL 着色器定义
   */
  
  const BasicVertexShader = `
    attribute vec3 aPosition;
    attribute vec3 aNormal;
    attribute vec3 aColor;
    uniform mat4 uMVP;
    
    varying vec3 vColor;
    varying vec3 vNormal;
    varying vec3 vWorldPos;
    
    void main() {
      gl_Position = uMVP * vec4(aPosition, 1.0);
      vColor = aColor;
      vNormal = aNormal;
      vWorldPos = aPosition;
    }
  `;
  
  const SolidFragmentShader = `
    precision mediump float;
    
    varying vec3 vColor;
    varying vec3 vNormal;
    varying vec3 vWorldPos;
    
    uniform vec3 uCameraPos;
    
    // 光照常量设置
    const vec3 lightDir = normalize(vec3(0.5, 0.9, 0.3)); // 太阳光方向
    const vec3 lightColor = vec3(1.0, 0.96, 0.88);        // 阳光颜色（偏暖）
    const vec3 ambientColor = vec3(0.4, 0.45, 0.5);       // 环境光（偏蓝/灰，模拟天光）
    const vec3 skyColor = vec3(0.53, 0.81, 0.98);         // 天空颜色，用于雾气混合
  
    void main() {
      vec3 texColor = vColor;
      vec3 localP = fract(vWorldPos);
  
      // 固体方块处理
      // 1. 像素化噪点
      vec3 blockCoord = floor(vWorldPos * 16.0);
      float noise = fract(sin(dot(blockCoord, vec3(12.9898, 78.233, 45.164))) * 43758.5453);
      texColor *= (0.94 + 0.12 * noise);
  
      // 2. 边缘伪环境光遮蔽 (Fake AO) - 极其微弱，仅提供一点体积感而不是网格线
      vec3 distToEdge = min(localP, 1.0 - localP);
      float edgeDist = 1.0;
      vec3 absNorm = abs(normalize(vNormal));
      if (absNorm.x > 0.5) edgeDist = min(distToEdge.y, distToEdge.z);
      else if (absNorm.y > 0.5) edgeDist = min(distToEdge.x, distToEdge.z);
      else edgeDist = min(distToEdge.x, distToEdge.y);
  
      // 极细的接缝：只有边缘 1% 范围内才受影响，且暗度只有 10%
      float ao = smoothstep(0.0, 0.015, edgeDist);
      texColor *= (0.90 + 0.10 * ao);
  
      // 3. 漫反射光照 (Lambert)
      vec3 norm = normalize(vNormal);
      float diff = max(dot(norm, lightDir), 0.0);
      vec3 diffuse = diff * lightColor;
  
      // 合并光照
      vec3 finalColor = (ambientColor + diffuse) * texColor;
  
      // 4. 距离雾 (Fog)
      float dist = length(uCameraPos - vWorldPos);
      float fogFactor = smoothstep(40.0, 80.0, dist);
      finalColor = mix(finalColor, skyColor, fogFactor);
  
      gl_FragColor = vec4(finalColor, 1.0);
    }
  `;
  
  /**
   * 玩家模型专用着色器
   * - uModel: 部件的世界变换矩阵（平移+旋转）
   * - uVP:    投影 * 视图矩阵（不含模型变换，单独传入）
   */
  const PlayerVertexShader = `
    attribute vec3 aPosition;
    attribute vec3 aNormal;
    attribute vec3 aColor;
  
    uniform mat4 uModel;  // 部件模型矩阵
    uniform mat4 uVP;     // View-Projection 矩阵
  
    varying vec3 vColor;
    varying vec3 vNormal;
    varying vec3 vWorldPos;
  
    void main() {
      vec4 worldPos = uModel * vec4(aPosition, 1.0);
      gl_Position = uVP * worldPos;
      vWorldPos = worldPos.xyz;
      vColor = aColor;
      // 法线变换：只需旋转部分（忽略非均匀缩放）
      vNormal = mat3(uModel) * aNormal;
    }
  `;
  
  const PlayerFragmentShader = `
    precision mediump float;
  
    varying vec3 vColor;
    varying vec3 vNormal;
    varying vec3 vWorldPos;
  
    uniform vec3 uCameraPos;
  
    const vec3 lightDir = normalize(vec3(0.5, 0.9, 0.3));
    const vec3 lightColor = vec3(1.0, 0.96, 0.88);
    const vec3 ambientColor = vec3(0.35, 0.4, 0.45);
    const vec3 skyColor = vec3(0.53, 0.81, 0.98);
  
    void main() {
      vec3 norm = normalize(vNormal);
      float diff = max(dot(norm, lightDir), 0.0);
      vec3 diffuse = diff * lightColor;
      vec3 finalColor = (ambientColor + diffuse) * vColor;
  
      // 距离雾
      float dist = length(uCameraPos - vWorldPos);
      float fogFactor = smoothstep(40.0, 80.0, dist);
      finalColor = mix(finalColor, skyColor, fogFactor);
  
      gl_FragColor = vec4(finalColor, 1.0);
    }
  `;
  
  /**
   * HUD 覆盖层着色器
   * 将一张 2D Canvas 纹理以正交投影全屏覆盖到 WebGL 画布上
   * aPosition: vec2，范围 [-1, 1]（NDC 坐标，直接省略矩阵运算）
   * aTexCoord: vec2，范围 [0, 1]
   */
  const HudVertexShader = `
    attribute vec2 aPosition;
    attribute vec2 aTexCoord;
    varying vec2 vTexCoord;
    void main() {
      gl_Position = vec4(aPosition, 0.0, 1.0);
      vTexCoord = aTexCoord;
    }
  `;
  
  const HudFragmentShader = `
    precision mediump float;
    varying vec2 vTexCoord;
    uniform sampler2D uTexture;
    void main() {
      gl_FragColor = texture2D(uTexture, vTexCoord);
    }
  `;
  
  const WaterFragmentShader = `
    precision mediump float;
    
    varying vec3 vColor;
    varying vec3 vNormal;
    varying vec3 vWorldPos;
    
    uniform vec3 uCameraPos;
    uniform float uTime;
    
    const vec3 lightDir = normalize(vec3(0.5, 0.9, 0.3));
    const vec3 lightColor = vec3(1.0, 0.96, 0.88);
    const vec3 ambientColor = vec3(0.4, 0.45, 0.5);
    const vec3 skyColor = vec3(0.53, 0.81, 0.98);
  
    void main() {
      vec3 texColor = vColor;
  
      vec3 norm = normalize(vNormal);
      float diff = max(dot(norm, lightDir), 0.0);
      
      // 水面特殊光照：增加一点高光反射感，减弱漫反射
      vec3 diffuse = diff * lightColor * 0.7 + vec3(0.1, 0.2, 0.3);
  
      // 合并光照
      vec3 finalColor = (ambientColor + diffuse) * texColor;
  
      // 雾气
      float dist = length(uCameraPos - vWorldPos);
      float fogFactor = smoothstep(40.0, 80.0, dist);
      finalColor = mix(finalColor, skyColor, fogFactor);
  
      // 水的透明度 (Alpha值越大，水越不透明)
      gl_FragColor = vec4(finalColor, 0.95);
    }
  `;
  
  module.exports.BasicVertexShader = BasicVertexShader;
  module.exports.SolidFragmentShader = SolidFragmentShader;
  module.exports.PlayerVertexShader = PlayerVertexShader;
  module.exports.PlayerFragmentShader = PlayerFragmentShader;
  module.exports.HudVertexShader = HudVertexShader;
  module.exports.HudFragmentShader = HudFragmentShader;
  module.exports.WaterFragmentShader = WaterFragmentShader;
  
  return module.exports;
})();

// Module: src\renderer.js
__modules[7] = (function() {
  const module = { exports: {} };
  /**
   * renderer.js - WebGL 渲染器
   * 负责编译着色器、管理缓冲区、绘制区块网格
   */
  
  const { Mat4 } = __modules[2];
  const { BasicVertexShader, SolidFragmentShader, WaterFragmentShader, HudVertexShader, HudFragmentShader } = __modules[8];
  
  /**
   * Renderer - WebGL 渲染器
   * 负责编译着色器、管理缓冲区、绘制区块网格
   */
  class Renderer {
    /**
     * @param {WebGLRenderingContext} gl
     * @param {number} width
     * @param {number} height
     */
    constructor(gl, width, height) {
      this.gl = gl;
      this.width = width;
      this.height = height;
      this.chunkBuffers = new Map(); // key: "cx,cz" => buffer set
      this._initGL();
    }
  
    _initGL() {
      const gl = this.gl;
      // 编译着色器程序
      this.solidProgram = this._createProgram(BasicVertexShader, SolidFragmentShader);
      this.waterProgram = this._createProgram(BasicVertexShader, WaterFragmentShader);
  
      // 获取 attribute / uniform 位置 (固体)
      this.solidLocations = {
        aPosition: gl.getAttribLocation(this.solidProgram, 'aPosition'),
        aNormal: gl.getAttribLocation(this.solidProgram, 'aNormal'),
        aColor: gl.getAttribLocation(this.solidProgram, 'aColor'),
        uMVP: gl.getUniformLocation(this.solidProgram, 'uMVP'),
        uCameraPos: gl.getUniformLocation(this.solidProgram, 'uCameraPos'),
      };
  
      // 获取 attribute / uniform 位置 (水面)
      this.waterLocations = {
        aPosition: gl.getAttribLocation(this.waterProgram, 'aPosition'),
        aNormal: gl.getAttribLocation(this.waterProgram, 'aNormal'),
        aColor: gl.getAttribLocation(this.waterProgram, 'aColor'),
        uMVP: gl.getUniformLocation(this.waterProgram, 'uMVP'),
        uCameraPos: gl.getUniformLocation(this.waterProgram, 'uCameraPos'),
        uTime: gl.getUniformLocation(this.waterProgram, 'uTime'),
      };
  
      // GL 状态
      gl.enable(gl.DEPTH_TEST);
      gl.enable(gl.CULL_FACE);
      gl.cullFace(gl.BACK);
  
      // 启用混合 (用于水面半透明)
      gl.enable(gl.BLEND);
      gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
  
      // 天空颜色
      gl.clearColor(0.53, 0.81, 0.98, 1.0);
  
      // ── HUD 覆盖层 ───────────────────────────────────────────────
      this.hudProgram = this._createProgram(HudVertexShader, HudFragmentShader);
      this.hudLocations = {
        aPosition: gl.getAttribLocation(this.hudProgram, 'aPosition'),
        aTexCoord: gl.getAttribLocation(this.hudProgram, 'aTexCoord'),
        uTexture:  gl.getUniformLocation(this.hudProgram, 'uTexture'),
      };
  
      // 全屏四边形（NDC 坐标，两个三角形覆盖全屏）
      // 注意：纹理 Y 轴翻转（Canvas 2D 坐标 Y 向下，WebGL 纹理 Y 向上）
      const quadPos = new Float32Array([
        -1, -1,   1, -1,   1,  1,
        -1, -1,   1,  1,  -1,  1,
      ]);
      const quadUV = new Float32Array([
        0, 1,   1, 1,   1, 0,
        0, 1,   1, 0,   0, 0,
      ]);
      this._hudPosBuf = gl.createBuffer();
      gl.bindBuffer(gl.ARRAY_BUFFER, this._hudPosBuf);
      gl.bufferData(gl.ARRAY_BUFFER, quadPos, gl.STATIC_DRAW);
  
      this._hudUVBuf = gl.createBuffer();
      gl.bindBuffer(gl.ARRAY_BUFFER, this._hudUVBuf);
      gl.bufferData(gl.ARRAY_BUFFER, quadUV, gl.STATIC_DRAW);
  
      // 预创建 HUD 纹理对象（每帧用 texImage2D 更新内容）
      this._hudTexture = gl.createTexture();
      gl.bindTexture(gl.TEXTURE_2D, this._hudTexture);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
      gl.bindTexture(gl.TEXTURE_2D, null);
    }
  
    // ---- 着色器编译 ----
  
    _compileShader(type, source) {
      const gl = this.gl;
      const shader = gl.createShader(type);
      gl.shaderSource(shader, source);
      gl.compileShader(shader);
      if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
        console.error('Shader compile error:', gl.getShaderInfoLog(shader));
        gl.deleteShader(shader);
        return null;
      }
      return shader;
    }
  
    _createProgram(vsSource, fsSource) {
      const gl = this.gl;
      const vs = this._compileShader(gl.VERTEX_SHADER, vsSource);
      const fs = this._compileShader(gl.FRAGMENT_SHADER, fsSource);
      const prog = gl.createProgram();
      gl.attachShader(prog, vs);
      gl.attachShader(prog, fs);
      gl.linkProgram(prog);
      if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) {
        console.error('Program link error:', gl.getProgramInfoLog(prog));
        return null;
      }
      return prog;
    }
  
    // ---- 缓冲区管理 ----
  
    _createBufferSet(mesh) {
      if (!mesh || mesh.indices.length === 0) return null;
      const gl = this.gl;
      
      const posBuf = gl.createBuffer();
      gl.bindBuffer(gl.ARRAY_BUFFER, posBuf);
      gl.bufferData(gl.ARRAY_BUFFER, mesh.positions, gl.STATIC_DRAW);
  
      const normBuf = gl.createBuffer();
      gl.bindBuffer(gl.ARRAY_BUFFER, normBuf);
      gl.bufferData(gl.ARRAY_BUFFER, mesh.normals, gl.STATIC_DRAW);
  
      const colBuf = gl.createBuffer();
      gl.bindBuffer(gl.ARRAY_BUFFER, colBuf);
      gl.bufferData(gl.ARRAY_BUFFER, mesh.colors, gl.STATIC_DRAW);
  
      const idxBuf = gl.createBuffer();
      gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, idxBuf);
      gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, mesh.indices, gl.STATIC_DRAW);
  
      return { posBuf, normBuf, colBuf, idxBuf, indexCount: mesh.indices.length };
    }
  
    _deleteBufferSet(buf) {
      if (!buf) return;
      const gl = this.gl;
      gl.deleteBuffer(buf.posBuf);
      gl.deleteBuffer(buf.normBuf);
      gl.deleteBuffer(buf.colBuf);
      gl.deleteBuffer(buf.idxBuf);
    }
  
    /**
     * 上传 Chunk 网格数据到 GPU
     * @param {string} key - "cx,cz"
     * @param {object} meshGroup - Chunk.buildMesh() 的返回值 (包含 solidMesh, waterMesh)
     */
    uploadChunkMesh(key, meshGroup) {
      // 如果已有旧缓冲区，先删除
      this.removeChunkMesh(key);
  
      this.chunkBuffers.set(key, {
        solid: this._createBufferSet(meshGroup.solidMesh),
        water: this._createBufferSet(meshGroup.waterMesh),
      });
    }
  
    /** 删除指定区块的 GPU 缓冲区 */
    removeChunkMesh(key) {
      if (this.chunkBuffers.has(key)) {
        const bufs = this.chunkBuffers.get(key);
        this._deleteBufferSet(bufs.solid);
        this._deleteBufferSet(bufs.water);
        this.chunkBuffers.delete(key);
      }
    }
  
    // ---- 渲染 ----
  
    _drawBufferSet(buf, locs) {
      if (!buf) return;
      const gl = this.gl;
  
      // Position
      gl.bindBuffer(gl.ARRAY_BUFFER, buf.posBuf);
      gl.enableVertexAttribArray(locs.aPosition);
      gl.vertexAttribPointer(locs.aPosition, 3, gl.FLOAT, false, 0, 0);
  
      // Normal
      gl.bindBuffer(gl.ARRAY_BUFFER, buf.normBuf);
      gl.enableVertexAttribArray(locs.aNormal);
      gl.vertexAttribPointer(locs.aNormal, 3, gl.FLOAT, false, 0, 0);
  
      // Color
      gl.bindBuffer(gl.ARRAY_BUFFER, buf.colBuf);
      gl.enableVertexAttribArray(locs.aColor);
      gl.vertexAttribPointer(locs.aColor, 3, gl.FLOAT, false, 0, 0);
  
      // Draw
      gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, buf.idxBuf);
      gl.drawElements(gl.TRIANGLES, buf.indexCount, gl.UNSIGNED_INT, 0);
    }
  
    /**
     * 渲染一帧
     * @param {Mat4} viewMatrix - 视图矩阵
     * @param {Mat4} projMatrix - 投影矩阵
     * @param {Vec3} cameraPos - 相机世界坐标（计算雾气需要）
     */
    render(viewMatrix, projMatrix, cameraPos) {
      const gl = this.gl;
      gl.viewport(0, 0, this.width, this.height);
      gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
  
      const mvp = projMatrix.multiply(viewMatrix);
  
      // 1. 渲染所有固体方块 (不透明)
      gl.useProgram(this.solidProgram);
      gl.uniformMatrix4fv(this.solidLocations.uMVP, false, mvp.m);
      if (cameraPos) {
        gl.uniform3f(this.solidLocations.uCameraPos, cameraPos.x, cameraPos.y, cameraPos.z);
      }
      for (const bufs of this.chunkBuffers.values()) {
        this._drawBufferSet(bufs.solid, this.solidLocations);
      }
  
      // 2. 渲染所有水面方块 (半透明)
      // 理想情况下应该根据深度排序，但为了简化，直接在固体之后渲染
      gl.useProgram(this.waterProgram);
      gl.uniformMatrix4fv(this.waterLocations.uMVP, false, mvp.m);
      if (cameraPos) {
        gl.uniform3f(this.waterLocations.uCameraPos, cameraPos.x, cameraPos.y, cameraPos.z);
      }
      gl.uniform1f(this.waterLocations.uTime, performance.now() / 1000.0);
      
      for (const bufs of this.chunkBuffers.values()) {
        this._drawBufferSet(bufs.water, this.waterLocations);
      }
  
      // 保存 VP 矩阵和相机位置，供外部（EntityRenderer / entity.js）使用
      this._vpMatrix   = projMatrix.multiply(viewMatrix);
      this._cameraPos  = cameraPos;
    }
  
    /**
     * 将离屏 2D Canvas 内容作为纹理覆盖到全屏（HUD 覆盖层）
     * @param {OffscreenCanvas|HTMLCanvasElement} hudCanvas - 包含 HUD 内容的 2D Canvas
     */
    drawHUD(hudCanvas) {
      if (!hudCanvas) return;
      const gl = this.gl;
  
      // 关闭深度测试，让 HUD 始终覆盖在 3D 内容上面
      gl.disable(gl.DEPTH_TEST);
  
      // 上传 Canvas 内容到纹理
      gl.bindTexture(gl.TEXTURE_2D, this._hudTexture);
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, hudCanvas);
  
      // 使用 HUD 着色器程序
      gl.useProgram(this.hudProgram);
  
      // 绑定顶点位置
      gl.bindBuffer(gl.ARRAY_BUFFER, this._hudPosBuf);
      gl.enableVertexAttribArray(this.hudLocations.aPosition);
      gl.vertexAttribPointer(this.hudLocations.aPosition, 2, gl.FLOAT, false, 0, 0);
  
      // 绑定纹理坐标
      gl.bindBuffer(gl.ARRAY_BUFFER, this._hudUVBuf);
      gl.enableVertexAttribArray(this.hudLocations.aTexCoord);
      gl.vertexAttribPointer(this.hudLocations.aTexCoord, 2, gl.FLOAT, false, 0, 0);
  
      // 绑定纹理到 unit 0
      gl.activeTexture(gl.TEXTURE0);
      gl.uniform1i(this.hudLocations.uTexture, 0);
  
      // 绘制全屏四边形（6 个顶点 = 2 个三角形）
      gl.drawArrays(gl.TRIANGLES, 0, 6);
  
      // 恢复深度测试
      gl.enable(gl.DEPTH_TEST);
      gl.bindTexture(gl.TEXTURE_2D, null);
    }
  
    /** 调整画布大小 */
    resize(width, height) {
      this.width = width;
      this.height = height;
    }
  }
  
  module.exports.Renderer = Renderer;;
  
  return module.exports;
})();

// Module: src\entity.js
__modules[9] = (function() {
  const module = { exports: {} };
  /**
   * entity.js - 实体系统 + 实体渲染器
   *
   * 层级结构：
   *   Entity            —— 所有可渲染生物的基类（位置、方向、速度、生命值）
   *     └─ HumanoidEntity —— 人形实体（头/身/臂/腿六部件骨骼模型）
   *          └─ Player   —— 玩家（在 player.js 中定义）
   *   EntityRenderer    —— 统一管理所有实体的 GPU 缓冲区与绘制
   *
   * 数据与渲染分离原则：
   *   - Entity / HumanoidEntity 只负责状态数据和骨骼动画计算
   *   - 实际 GPU 上传与绘制由同文件的 EntityRenderer 完成
   */
  
  const { Vec3 } = __modules[2];
  
  // ─────────────────────────────────────────────
  // 工具函数：构建盒体部件几何数据
  // ─────────────────────────────────────────────
  
  /**
   * 生成一个以原点为中心的长方体的顶点/法线/颜色/索引数组
   * @param {number} w  宽 (X)
   * @param {number} h  高 (Y)
   * @param {number} d  深 (Z)
   * @param {number[]} color  [r, g, b]  0~1
   * @returns {{ positions: Float32Array, normals: Float32Array, colors: Float32Array, indices: Uint16Array }}
   */
  function buildBoxGeometry(w, h, d, color) {
    const hw = w / 2, hh = h / 2, hd = d / 2;
    const [r, g, b] = color;
  
    const faceData = [
      { n: [1,  0, 0], v: [[ hw,-hh,-hd],[ hw, hh,-hd],[ hw, hh, hd],[ hw,-hh, hd]] },
      { n: [-1, 0, 0], v: [[-hw,-hh, hd],[-hw, hh, hd],[-hw, hh,-hd],[-hw,-hh,-hd]] },
      { n: [0,  1, 0], v: [[-hw, hh,-hd],[ hw, hh,-hd],[ hw, hh, hd],[-hw, hh, hd]] },
      { n: [0, -1, 0], v: [[-hw,-hh, hd],[ hw,-hh, hd],[ hw,-hh,-hd],[-hw,-hh,-hd]] },
      { n: [0,  0, 1], v: [[-hw,-hh, hd],[-hw, hh, hd],[ hw, hh, hd],[ hw,-hh, hd]] },
      { n: [0,  0,-1], v: [[ hw,-hh,-hd],[ hw, hh,-hd],[-hw, hh,-hd],[-hw,-hh,-hd]] },
    ];
  
    const positions = [], normals = [], colors = [], indices = [];
    let idx = 0;
  
    for (const face of faceData) {
      // 顶面稍微提亮，底面稍暗，增加层次感
      const bright = face.n[1] > 0.5 ? 1.15 : (face.n[1] < -0.5 ? 0.75 : 1.0);
      for (const [vx, vy, vz] of face.v) {
        positions.push(vx, vy, vz);
        normals.push(face.n[0], face.n[1], face.n[2]);
        colors.push(r * bright, g * bright, b * bright);
      }
      indices.push(idx, idx + 1, idx + 2, idx, idx + 2, idx + 3);
      idx += 4;
    }
  
    return {
      positions: new Float32Array(positions),
      normals:   new Float32Array(normals),
      colors:    new Float32Array(colors),
      indices:   new Uint16Array(indices),
    };
  }
  
  /**
   * 构建部件的模型矩阵（列主序，供 WebGL uniformMatrix4fv 使用）
   * 变换顺序：先绕 X 轴旋转（摆动），再绕 Y 轴旋转（朝向），再平移
   * @param {number} tx, ty, tz  世界坐标（部件中心）
   * @param {number} yaw         绕 Y 轴旋转（朝向）
   * @param {number} pitchX      绕 X 轴旋转（手臂/腿摆动角度）
   * @returns {Float32Array} 4x4 列主序矩阵
   */
  function buildPartModelMatrix(tx, ty, tz, yaw, pitchX) {
    const cy = Math.cos(yaw),    sy = Math.sin(yaw);
    const cx = Math.cos(pitchX), sx = Math.sin(pitchX);
  
    // R = Ry * Rx
    const m = new Float32Array(16);
    m[0]  =  cy;      m[1]  =  sy * sx;  m[2]  = -sy * cx;  m[3]  = 0;
    m[4]  =  0;       m[5]  =  cx;       m[6]  =  sx;        m[7]  = 0;
    m[8]  =  sy;      m[9]  = -cy * sx;  m[10] =  cy * cx;   m[11] = 0;
    m[12] =  tx;      m[13] =  ty;       m[14] =  tz;        m[15] = 1;
    return m;
  }
  
  // ─────────────────────────────────────────────
  // Entity — 所有实体的基类
  // ─────────────────────────────────────────────
  
  /**
   * Entity 基类
   *
   * 子类需实现：
   *   getModelParts()  —— 返回当前帧的骨骼部件列表
   *   getBoundingBox() —— 返回 AABB 包围盒 { minX, maxX, minY, maxY, minZ, maxZ }
   */
  class Entity {
    /**
     * @param {number} x
     * @param {number} y
     * @param {number} z
     */
    constructor(x, y, z) {
      /** 世界坐标（脚底中心） */
      this.position = new Vec3(x, y, z);
      /** 速度 */
      this.velocity = new Vec3(0, 0, 0);
      /** 水平朝向（绕 Y 轴，弧度） */
      this.yaw = 0;
      /** 垂直俯仰（绕 X 轴，弧度） */
      this.pitch = 0;
      /** 生命值（0 = 死亡） */
      this.health = 20;
      /** 是否在地面 */
      this.onGround = false;
      /** 是否活跃（false 时跳过更新和渲染） */
      this.alive = true;
    }
  
    /**
     * 获取朝向的前方向向量（水平）
     * @returns {Vec3}
     */
    getForward() {
      return new Vec3(-Math.sin(this.yaw), 0, -Math.cos(this.yaw)).normalize();
    }
  
    /**
     * 获取朝向的右方向向量（水平）
     * @returns {Vec3}
     */
    getRight() {
      return new Vec3(Math.cos(this.yaw), 0, -Math.sin(this.yaw)).normalize();
    }
  
    /**
     * 获取视线方向（3D，结合 yaw 和 pitch）
     * @returns {Vec3}
     */
    getLookDir() {
      return new Vec3(
        -Math.sin(this.yaw) * Math.cos(this.pitch),
         Math.sin(this.pitch),
        -Math.cos(this.yaw) * Math.cos(this.pitch),
      ).normalize();
    }
  
    /**
     * 获取 AABB 包围盒（子类重写以提供自定义尺寸）
     * @returns {{ hw: number, hd: number, height: number }}
     */
    getBoundingBox() {
      return { hw: 0.3, hd: 0.3, height: 1.6 };
    }
  
    /**
     * 返回当前帧要渲染的骨骼部件列表
     * 每个部件：{ positions, normals, colors, indices, modelMatrix }
     * 子类必须重写此方法
     * @returns {Array}
     */
    getModelParts() {
      return [];
    }
  }
  
  // ─────────────────────────────────────────────
  // HumanoidEntity — 人形实体（六部件骨骼）
  // ─────────────────────────────────────────────
  
  /**
   * HumanoidEntity 人形实体定义
   *
   * 骨骼描述结构（SKELETON）用于定义各部件的：
   *   - size:   [w, h, d]        以格为单位
   *   - color:  [r, g, b]        0~1
   *   - pivot:  'top'|'bottom'   旋转轴（摆动时绕顶端还是底端）
   *   - attach: 相对于脚底的 Y 偏移基准（由 layout 自动算）
   *
   * 子类可通过覆盖 SKELETON 来定制外观（不同皮肤/体型）
   * 而 getModelParts() 逻辑保持通用
   */
  class HumanoidEntity extends Entity {
    /**
     * @param {number} x
     * @param {number} y  脚底 Y 坐标
     * @param {number} z
     * @param {object} options
     * @param {object} [options.skeleton]  可选骨骼覆盖（不传则使用默认玩家外观）
     */
    constructor(x, y, z, options = {}) {
      super(x, y, z);
      this.skeleton = options.skeleton || HumanoidEntity.DEFAULT_SKELETON;
    }
  
    /**
     * 默认玩家外观骨骼描述
     * 采用 Minecraft 原版比例
     */
    static DEFAULT_SKELETON = {
      head: {
        size:  [0.50, 0.50, 0.50],
        color: [0.88, 0.71, 0.51],  // 肤色
      },
      body: {
        size:  [0.50, 0.75, 0.25],
        color: [0.25, 0.45, 0.75],  // 蓝色衬衫
      },
      leftArm: {
        size:  [0.25, 0.75, 0.25],
        color: [0.88, 0.71, 0.51],  // 肤色
      },
      rightArm: {
        size:  [0.25, 0.75, 0.25],
        color: [0.88, 0.71, 0.51],
      },
      leftLeg: {
        size:  [0.25, 0.75, 0.25],
        color: [0.15, 0.22, 0.55],  // 深蓝裤子
      },
      rightLeg: {
        size:  [0.25, 0.75, 0.25],
        color: [0.15, 0.22, 0.55],
      },
    };
  
    getBoundingBox() {
      const sk = this.skeleton;
      return {
        hw:     sk.body.size[0] / 2,
        hd:     sk.body.size[2] / 2,
        height: sk.leftLeg.size[1] + sk.body.size[1] + sk.head.size[1],
      };
    }
  
    /**
     * 计算并返回当前帧的六部件列表
     * 包含行走动画（腿/手臂摆动）
     */
    getModelParts() {
      const sk = this.skeleton;
      const px = this.position.x;
      const py = this.position.y; // 脚底 Y
      const pz = this.position.z;
      const yaw = this.yaw;
  
      const [, LEG_H]  = sk.leftLeg.size;
      const [BODY_W, BODY_H] = sk.body.size;
      const [HEAD_W, HEAD_H] = sk.head.size;
      const [ARM_W, ARM_H]   = sk.leftArm.size;
      const [LEG_W]          = sk.leftLeg.size;
  
      // 行走摆动：根据水平速度决定是否播放动画
      const moving = Math.abs(this.velocity.x) + Math.abs(this.velocity.z) > 0.1;
      const swing  = moving ? Math.sin(performance.now() / 180) * 0.4 : 0;
  
      const parts = [];
  
      // ── 头部 ──────────────────────────────────
      parts.push(this._makePart(
        sk.head,
        px,
        py + LEG_H + BODY_H + HEAD_H * 0.5,
        pz,
        yaw, 0,
      ));
  
      // ── 身体 ──────────────────────────────────
      parts.push(this._makePart(
        sk.body,
        px,
        py + LEG_H + BODY_H * 0.5,
        pz,
        yaw, 0,
      ));
  
      // ── 左臂（玩家视角右侧） ──────────────────
      const armOffX = BODY_W * 0.5 + ARM_W * 0.5;
      parts.push(this._makePart(
        sk.leftArm,
        px + Math.cos(yaw) * armOffX,
        py + LEG_H + ARM_H * 0.5,
        pz - Math.sin(yaw) * armOffX,
        yaw, -swing,
      ));
  
      // ── 右臂 ──────────────────────────────────
      parts.push(this._makePart(
        sk.rightArm,
        px - Math.cos(yaw) * armOffX,
        py + LEG_H + ARM_H * 0.5,
        pz + Math.sin(yaw) * armOffX,
        yaw, swing,
      ));
  
      // ── 左腿 ──────────────────────────────────
      const legOffX = LEG_W * 0.5;
      parts.push(this._makePart(
        sk.leftLeg,
        px + Math.cos(yaw) * legOffX,
        py + LEG_H * 0.5,
        pz - Math.sin(yaw) * legOffX,
        yaw, swing,
      ));
  
      // ── 右腿 ──────────────────────────────────
      parts.push(this._makePart(
        sk.rightLeg,
        px - Math.cos(yaw) * legOffX,
        py + LEG_H * 0.5,
        pz + Math.sin(yaw) * legOffX,
        yaw, -swing,
      ));
  
      return parts;
    }
  
    /**
     * 根据骨骼部件描述构建几何数据 + 模型矩阵
     * @param {object} boneDef  骨骼描述 { size, color }
     * @param {number} wx,wy,wz 世界坐标（部件中心）
     * @param {number} yaw
     * @param {number} pitchX   摆动角度
     */
    _makePart(boneDef, wx, wy, wz, yaw, pitchX) {
      const [w, h, d] = boneDef.size;
      const geo = buildBoxGeometry(w, h, d, boneDef.color);
      const modelMatrix = buildPartModelMatrix(wx, wy, wz, yaw, pitchX);
      return { ...geo, modelMatrix };
    }
  }
  
  // ─────────────────────────────────────────────
  // EntityRenderer — 实体专属渲染器
  // ─────────────────────────────────────────────
  
  const { PlayerVertexShader, PlayerFragmentShader } = __modules[8];
  
  /**
   * EntityRenderer
   *
   * 使用 PlayerVertexShader / PlayerFragmentShader 渲染所有人形实体。
   * 预分配持久 GPU Buffer（bufferSubData 更新，避免每帧 create/delete）。
   *
   * 使用方式：
   *   const er = new EntityRenderer(gl);
   *   // 每帧：
   *   er.drawEntities(entities, vpMatrix, cameraPos);
   *
   * 如果未来需要不同外观的实体（怪物等），可在此扩展为多 Program 管理。
   */
  class EntityRenderer {
    /**
     * @param {WebGLRenderingContext} gl
     */
    constructor(gl) {
      this.gl = gl;
      this._program = null;
      this._locs = null;
  
      // 预分配容量：最多同屏 64 个实体
      // 人形：6部件 * 24顶点 = 144顶点，6部件 * 36索引 = 216索引
      this._MAX_ENTITIES   = 64;
      this._VERTS_PER_ENTITY = 6 * 24;
      this._IDX_PER_ENTITY   = 6 * 36;
  
      this._posBuf  = null;
      this._normBuf = null;
      this._colBuf  = null;
      this._idxBuf  = null;
  
      this._init();
    }
  
    // ─── 初始化 ───────────────────────────────────────────────────────────────
  
    _init() {
      const gl = this.gl;
  
      this._program = this._createProgram(PlayerVertexShader, PlayerFragmentShader);
      const p = this._program;
  
      this._locs = {
        aPosition:  gl.getAttribLocation(p, 'aPosition'),
        aNormal:    gl.getAttribLocation(p, 'aNormal'),
        aColor:     gl.getAttribLocation(p, 'aColor'),
        uModel:     gl.getUniformLocation(p, 'uModel'),
        uVP:        gl.getUniformLocation(p, 'uVP'),
        uCameraPos: gl.getUniformLocation(p, 'uCameraPos'),
      };
  
      const maxV = this._MAX_ENTITIES * this._VERTS_PER_ENTITY;
      const maxI = this._MAX_ENTITIES * this._IDX_PER_ENTITY;
  
      this._posBuf  = this._allocBuffer(gl.ARRAY_BUFFER,         maxV * 3, Float32Array, gl.DYNAMIC_DRAW);
      this._normBuf = this._allocBuffer(gl.ARRAY_BUFFER,         maxV * 3, Float32Array, gl.DYNAMIC_DRAW);
      this._colBuf  = this._allocBuffer(gl.ARRAY_BUFFER,         maxV * 3, Float32Array, gl.DYNAMIC_DRAW);
      this._idxBuf  = this._allocBuffer(gl.ELEMENT_ARRAY_BUFFER, maxI,     Uint16Array,  gl.DYNAMIC_DRAW);
    }
  
    _allocBuffer(target, count, TypedArray, usage) {
      const gl = this.gl;
      const buf = gl.createBuffer();
      gl.bindBuffer(target, buf);
      gl.bufferData(target, new TypedArray(count), usage);
      return buf;
    }
  
    // ─── 主绘制接口 ────────────────────────────────────────────────────────────
  
    /**
     * 绘制所有实体
     * @param {Entity[]} entities  实体数组
     * @param {Mat4}     vpMatrix  View-Projection 矩阵
     * @param {Vec3}     cameraPos 相机世界坐标（雾气计算）
     */
    drawEntities(entities, vpMatrix, cameraPos) {
      if (!entities || entities.length === 0) return;
  
      const gl = this.gl;
      gl.useProgram(this._program);
      const locs = this._locs;
  
      gl.uniformMatrix4fv(locs.uVP, false, vpMatrix.m);
      if (cameraPos) {
        gl.uniform3f(locs.uCameraPos, cameraPos.x, cameraPos.y, cameraPos.z);
      }
  
      this._bindAttrib(this._posBuf,  locs.aPosition, 3);
      this._bindAttrib(this._normBuf, locs.aNormal,   3);
      this._bindAttrib(this._colBuf,  locs.aColor,    3);
      gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, this._idxBuf);
  
      for (const entity of entities) {
        if (!entity.alive) continue;
        const parts = entity.getModelParts();
        if (!parts || parts.length === 0) continue;
        this._drawEntityParts(parts, locs);
      }
    }
  
    _drawEntityParts(parts, locs) {
      const gl = this.gl;
  
      for (const part of parts) {
        gl.uniformMatrix4fv(locs.uModel, false, part.modelMatrix);
  
        gl.bindBuffer(gl.ARRAY_BUFFER, this._posBuf);
        gl.bufferSubData(gl.ARRAY_BUFFER, 0, part.positions);
  
        gl.bindBuffer(gl.ARRAY_BUFFER, this._normBuf);
        gl.bufferSubData(gl.ARRAY_BUFFER, 0, part.normals);
  
        gl.bindBuffer(gl.ARRAY_BUFFER, this._colBuf);
        gl.bufferSubData(gl.ARRAY_BUFFER, 0, part.colors);
  
        this._bindAttrib(this._posBuf,  locs.aPosition, 3);
        this._bindAttrib(this._normBuf, locs.aNormal,   3);
        this._bindAttrib(this._colBuf,  locs.aColor,    3);
  
        gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, this._idxBuf);
        gl.bufferSubData(gl.ELEMENT_ARRAY_BUFFER, 0, part.indices);
  
        gl.drawElements(gl.TRIANGLES, part.indices.length, gl.UNSIGNED_SHORT, 0);
      }
    }
  
    // ─── 工具方法 ──────────────────────────────────────────────────────────────
  
    _bindAttrib(buf, loc, size) {
      const gl = this.gl;
      gl.bindBuffer(gl.ARRAY_BUFFER, buf);
      gl.enableVertexAttribArray(loc);
      gl.vertexAttribPointer(loc, size, gl.FLOAT, false, 0, 0);
    }
  
    _compileShader(type, source) {
      const gl = this.gl;
      const shader = gl.createShader(type);
      gl.shaderSource(shader, source);
      gl.compileShader(shader);
      if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
        console.error('[EntityRenderer] Shader compile error:', gl.getShaderInfoLog(shader));
        gl.deleteShader(shader);
        return null;
      }
      return shader;
    }
  
    _createProgram(vsSource, fsSource) {
      const gl = this.gl;
      const vs = this._compileShader(gl.VERTEX_SHADER, vsSource);
      const fs = this._compileShader(gl.FRAGMENT_SHADER, fsSource);
      const prog = gl.createProgram();
      gl.attachShader(prog, vs);
      gl.attachShader(prog, fs);
      gl.linkProgram(prog);
      if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) {
        console.error('[EntityRenderer] Program link error:', gl.getProgramInfoLog(prog));
        return null;
      }
      return prog;
    }
  
    /** 释放所有 GPU 资源 */
    dispose() {
      const gl = this.gl;
      gl.deleteBuffer(this._posBuf);
      gl.deleteBuffer(this._normBuf);
      gl.deleteBuffer(this._colBuf);
      gl.deleteBuffer(this._idxBuf);
      gl.deleteProgram(this._program);
    }
  }
  
  module.exports.buildBoxGeometry = buildBoxGeometry;
  module.exports.buildPartModelMatrix = buildPartModelMatrix;
  module.exports.Entity = Entity;
  module.exports.HumanoidEntity = HumanoidEntity;
  module.exports.EntityRenderer = EntityRenderer;
  
  return module.exports;
})();

// Module: src\player.js
__modules[10] = (function() {
  const module = { exports: {} };
  /**
   * player.js - 玩家与相机系统
   *
   * Player 继承自 HumanoidEntity，专注于：
   *   - 输入状态管理
   *   - 第一/第三人称相机
   *   - 物理模拟（重力、碰撞、水中浮力）
   *   - 射线检测（方块交互）
   *
   * 模型渲染数据由父类 HumanoidEntity.getModelParts() 提供
   * GPU 上传与绘制由 EntityRenderer（entity.js）负责
   */
  
  const { Vec3, Mat4 } = __modules[2];
  const { Blocks } = __modules[5];
  const { HumanoidEntity } = __modules[9];
  
  // ─── 物理常量 ─────────────────────────────────────────────────────────────────
  const MOVE_SPEED       = 6.0;
  const SWIM_SPEED       = 4.0;
  const MOUSE_SENSITIVITY = 0.002;
  const GRAVITY          = -20.0;
  const JUMP_SPEED       = 8.0;
  const SWIM_JUMP_SPEED  = 6.0;
  const WATER_BUOYANCY   = 8.0;
  const WATER_DRAG       = 3.0;
  
  /** 玩家包围盒（半宽/高） */
  const PLAYER_HEIGHT = 1.6;
  const PLAYER_RADIUS = 0.3;
  
  // ─── 相机常量 ─────────────────────────────────────────────────────────────────
  const THIRD_PERSON_DIST = 5.0;
  const THIRD_PERSON_UP   = 1.0;
  const CAMERA_MODE_FIRST = 'first';
  const CAMERA_MODE_THIRD = 'third';
  
  /** 不可碰撞方块集合（空气 + 水） */
  const NON_SOLID_IDS = new Set([0, Blocks.WATER]);
  
  // ─────────────────────────────────────────────────────────────────────────────
  
  class Player extends HumanoidEntity {
    /**
     * @param {number} x
     * @param {number} y  脚底 Y 坐标
     * @param {number} z
     * @param {object} [options]
     * @param {object} [options.skeleton]  可选骨骼覆盖，用于自定义皮肤/体型
     */
    constructor(x, y, z, options = {}) {
      super(x, y, z, options);
  
      // Player.position 语义为"玩家身体中心（含身高偏移）"，保持向后兼容
      this.position.y += PLAYER_HEIGHT;
  
      // 视角模式
      this.cameraMode = CAMERA_MODE_FIRST;
  
      // ── 输入状态 ──────────────────────────────
      this.inputForward       = false;
      this.inputBackward      = false;
      this.inputLeft          = false;
      this.inputRight         = false;
      this.inputJump          = false;
      this.inputToggleCamera  = false;  // F 键
  
      // ── 方块交互 ──────────────────────────────
      this.clickLeft      = false;  // 左键：破坏
      this.clickRight     = false;  // 右键：放置
      this.blockSelectKey = 0;      // 数字键（0 = 无）
    }
  
    // ─── 包围盒 ───────────────────────────────────────────────────────────────
  
    getBoundingBox() {
      return { hw: PLAYER_RADIUS, hd: PLAYER_RADIUS, height: PLAYER_HEIGHT };
    }
  
    // ─── 相机 ─────────────────────────────────────────────────────────────────
  
    /** 切换视角模式（first ↔ third） */
    toggleCameraMode() {
      this.cameraMode = this.cameraMode === CAMERA_MODE_FIRST
        ? CAMERA_MODE_THIRD
        : CAMERA_MODE_FIRST;
    }
  
    /** 是否第三人称 */
    isThirdPerson() {
      return this.cameraMode === CAMERA_MODE_THIRD;
    }
  
    /**
     * 获取相机信息（视图矩阵 + 眼睛世界坐标）
     * @param {object|null} world  用于弹簧臂碰墙检测；传 null 则跳过碰撞
     * @returns {{ eye: Vec3, viewMatrix: Mat4 }}
     */
    getCameraInfo(world) {
      // 眼睛位置（略低于头顶）
      const eyePos = new Vec3(
        this.position.x,
        this.position.y - PLAYER_HEIGHT * 0.1,
        this.position.z,
      );
  
      if (this.cameraMode === CAMERA_MODE_FIRST) {
        const dir    = this.getLookDir();
        const center = eyePos.add(dir);
        return {
          eye:        eyePos,
          viewMatrix: Mat4.lookAt(eyePos, center, new Vec3(0, 1, 0)),
        };
      }
  
      // ── 第三人称：弹簧臂 ──────────────────────
      const dir     = this.getLookDir();
      const backDir = new Vec3(-dir.x, -dir.y, -dir.z);
  
      let actualDist = THIRD_PERSON_DIST;
      if (world) {
        const stepCount = Math.ceil(THIRD_PERSON_DIST * 2);
        for (let i = 1; i <= stepCount; i++) {
          const t    = (i / stepCount) * THIRD_PERSON_DIST;
          const upOff = THIRD_PERSON_UP * (t / THIRD_PERSON_DIST);
          const blockId = world.getBlock(
            Math.floor(eyePos.x + backDir.x * t),
            Math.floor(eyePos.y + backDir.y * t + upOff),
            Math.floor(eyePos.z + backDir.z * t),
          );
          if (blockId !== 0 && blockId !== Blocks.WATER) {
            actualDist = Math.max(0.5, t - 0.3);
            break;
          }
        }
      }
  
      const camEye = new Vec3(
        eyePos.x + backDir.x * actualDist,
        eyePos.y + backDir.y * actualDist + THIRD_PERSON_UP,
        eyePos.z + backDir.z * actualDist,
      );
      return {
        eye:        camEye,
        viewMatrix: Mat4.lookAt(camEye, eyePos, new Vec3(0, 1, 0)),
      };
    }
  
    /** 向后兼容：仅返回视图矩阵（第一人称） */
    getViewMatrix() {
      return this.getCameraInfo(null).viewMatrix;
    }
  
    // ─── 物理更新 ─────────────────────────────────────────────────────────────
  
    /**
     * 每帧更新：输入 → 速度 → 碰撞 → 落水 → 重力
     * @param {number} dt    帧间隔（秒）
     * @param {object} world World 对象
     */
    update(dt, world) {
      const forward = this.getForward();
      const right   = this.getRight();
      const moveDir = new Vec3(0, 0, 0);
  
      if (this.inputForward)  { moveDir.x += forward.x; moveDir.z += forward.z; }
      if (this.inputBackward) { moveDir.x -= forward.x; moveDir.z -= forward.z; }
      if (this.inputRight)    { moveDir.x += right.x;   moveDir.z += right.z; }
      if (this.inputLeft)     { moveDir.x -= right.x;   moveDir.z -= right.z; }
  
      const inWater = this._isInWater(world);
      const speed   = inWater ? SWIM_SPEED : MOVE_SPEED;
  
      if (moveDir.length() > 0) {
        const norm      = moveDir.normalize();
        this.velocity.x = norm.x * speed;
        this.velocity.z = norm.z * speed;
      } else {
        const drag      = inWater ? Math.max(0, 1 - WATER_DRAG * dt) : 0;
        this.velocity.x *= drag;
        this.velocity.z *= drag;
        if (!inWater) { this.velocity.x = 0; this.velocity.z = 0; }
      }
  
      if (this.inputJump) {
        if (inWater) {
          if (this.velocity.y < SWIM_JUMP_SPEED) this.velocity.y = SWIM_JUMP_SPEED;
        } else if (this.onGround) {
          this.velocity.y = JUMP_SPEED;
          this.onGround   = false;
        }
      }
  
      if (inWater) {
        this.velocity.y += (GRAVITY + WATER_BUOYANCY) * dt;
        this.velocity.y  = Math.max(-2.0, Math.min(4.0, this.velocity.y));
      } else {
        this.velocity.y += GRAVITY * dt;
      }
  
      const newPos = this.position.add(this.velocity.scale(dt));
      this._collide(newPos, world);
  
      // 掉出世界底部时重置
      if (this.position.y < -10) {
        this.position.y = 80;
        this.velocity.y = 0;
      }
  
      // 单帧消费的输入标志位——用完即清零，防止下一帧残留
      this.inputJump          = false;
      this.clickLeft          = false;
      this.clickRight         = false;
      this.inputToggleCamera  = false;
      this.blockSelectKey     = 0;
    }
  
    // ─── 碰撞 ─────────────────────────────────────────────────────────────────
  
    _isInWater(world) {
      const feetY = Math.floor(this.position.y - PLAYER_HEIGHT);
      const headY = Math.floor(this.position.y);
      for (let y = feetY; y <= headY; y++) {
        if (world.getBlock(Math.floor(this.position.x), y, Math.floor(this.position.z)) === Blocks.WATER) {
          return true;
        }
      }
      return false;
    }
  
    _collide(newPos, world) {
      const feetY      = newPos.y - PLAYER_HEIGHT;
      const blockBelow = world.getBlock(Math.floor(newPos.x), Math.floor(feetY), Math.floor(newPos.z));
  
      this.position.x = newPos.x;
      this.position.z = newPos.z;
      this._checkHorizontalCollision(world);
  
      if (this.velocity.y <= 0) {
        if (!NON_SOLID_IDS.has(blockBelow)) {
          this.position.y = Math.floor(feetY) + 1 + PLAYER_HEIGHT;
          this.velocity.y = 0;
          this.onGround   = true;
        } else {
          this.position.y = newPos.y;
          this.onGround   = false;
        }
      } else {
        const headY      = newPos.y + 0.2;
        const blockAbove = world.getBlock(Math.floor(this.position.x), Math.floor(headY), Math.floor(this.position.z));
        if (!NON_SOLID_IDS.has(blockAbove)) {
          this.velocity.y = 0;
        } else {
          this.position.y = newPos.y;
        }
        this.onGround = false;
      }
    }
  
    _checkHorizontalCollision(world) {
      const r      = PLAYER_RADIUS;
      const feetY  = Math.floor(this.position.y - PLAYER_HEIGHT);
      const bodyY  = Math.floor(this.position.y);
      const corners = [
        [this.position.x - r, this.position.z - r],
        [this.position.x + r, this.position.z - r],
        [this.position.x - r, this.position.z + r],
        [this.position.x + r, this.position.z + r],
      ];
  
      for (const [cx, cz] of corners) {
        for (let y = feetY; y <= bodyY; y++) {
          const b = world.getBlock(Math.floor(cx), y, Math.floor(cz));
          if (!NON_SOLID_IDS.has(b)) {
            const bx = Math.floor(cx) + 0.5;
            const bz = Math.floor(cz) + 0.5;
            const dx = this.position.x - bx;
            const dz = this.position.z - bz;
            if (Math.abs(dx) > Math.abs(dz)) {
              this.position.x = bx + (dx > 0 ? 0.5 + r : -0.5 - r);
            } else {
              this.position.z = bz + (dz > 0 ? 0.5 + r : -0.5 - r);
            }
          }
        }
      }
    }
  
    // ─── 输入 ─────────────────────────────────────────────────────────────────
  
    /** 鼠标移动（dx / dy 为像素偏移） */
    onMouseMove(dx, dy) {
      this.yaw   -= dx * MOUSE_SENSITIVITY;
      this.pitch -= dy * MOUSE_SENSITIVITY;
      this.pitch  = Math.max(-Math.PI / 2 + 0.01, Math.min(Math.PI / 2 - 0.01, this.pitch));
    }
  
    // ─── 射线检测 ─────────────────────────────────────────────────────────────
  
    /**
     * DDA 射线检测：沿视线方向找到第一个固体方块
     * @param {object} world
     * @param {number} maxDist
     * @returns {{ hit: [x,y,z], normal: [nx,ny,nz], blockId: number } | null}
     */
    raycast(world, maxDist = 6) {
      const dir = this.getLookDir();
  
      const originX = this.position.x;
      const originY = this.position.y - PLAYER_HEIGHT * 0.4;
      const originZ = this.position.z;
  
      let x = Math.floor(originX), y = Math.floor(originY), z = Math.floor(originZ);
  
      const stepX = dir.x > 0 ? 1 : (dir.x < 0 ? -1 : 0);
      const stepY = dir.y > 0 ? 1 : (dir.y < 0 ? -1 : 0);
      const stepZ = dir.z > 0 ? 1 : (dir.z < 0 ? -1 : 0);
  
      const tDeltaX = dir.x !== 0 ? Math.abs(1 / dir.x) : Infinity;
      const tDeltaY = dir.y !== 0 ? Math.abs(1 / dir.y) : Infinity;
      const tDeltaZ = dir.z !== 0 ? Math.abs(1 / dir.z) : Infinity;
  
      let tMaxX = dir.x !== 0 ? ((stepX > 0 ? x + 1 : x) - originX) / dir.x : Infinity;
      let tMaxY = dir.y !== 0 ? ((stepY > 0 ? y + 1 : y) - originY) / dir.y : Infinity;
      let tMaxZ = dir.z !== 0 ? ((stepZ > 0 ? z + 1 : z) - originZ) / dir.z : Infinity;
  
      let prevX = x, prevY = y, prevZ = z;
      const maxSteps = Math.ceil(maxDist) * 3;
  
      for (let i = 0; i < maxSteps; i++) {
        prevX = x; prevY = y; prevZ = z;
  
        if (tMaxX < tMaxY && tMaxX < tMaxZ) {
          if (tMaxX > maxDist) break;
          x += stepX; tMaxX += tDeltaX;
        } else if (tMaxY < tMaxZ) {
          if (tMaxY > maxDist) break;
          y += stepY; tMaxY += tDeltaY;
        } else {
          if (tMaxZ > maxDist) break;
          z += stepZ; tMaxZ += tDeltaZ;
        }
  
        const blockId = world.getBlock(x, y, z);
        if (!NON_SOLID_IDS.has(blockId)) {
          return {
            hit:     [x, y, z],
            normal:  [prevX - x, prevY - y, prevZ - z],
            blockId,
          };
        }
      }
  
      return null;
    }
  
    // ─── 模型部件（覆盖父类，使用 position.y - PLAYER_HEIGHT 作为脚底） ──────────
  
    /**
     * 覆盖 HumanoidEntity.getModelParts()
     * 因为 Player.position.y 是带身高偏移的中心位置，需减回脚底
     */
    getModelParts() {
      // 暂存原始 position.y，临时换为脚底 Y 让父类逻辑正确定位各部件
      const savedY       = this.position.y;
      this.position.y    = savedY - PLAYER_HEIGHT;
      const parts        = super.getModelParts();
      this.position.y    = savedY;
      return parts;
    }
  }
  
  module.exports.Player = Player;;
  
  module.exports.PLAYER_HEIGHT = PLAYER_HEIGHT;
  
  return module.exports;
})();

// Module: src\input.js
__modules[11] = (function() {
  const module = { exports: {} };
  /**
   * input.js - 统一输入层
   *
   * 桌面：
   *   - 键盘 WASD / Space / 1-5 / F
   *   - 鼠标锁定后旋转视角，左右键负责挖/放
   *   - 未锁定时可点击 HUD 上的按钮与快捷栏
   *
   * 触摸：
   *   - 左侧区域：虚拟摇杆移动
   *   - 右侧区域：滑动旋转视角
   *   - 右下角三个动作按钮：跳 / 挖 / 放
   *   - 底部快捷栏：点击切换方块
   */
  
  const JOYSTICK_RADIUS_RATIO = 0.095;
  const JOYSTICK_CENTER_X_RATIO = 0.18;
  const JOYSTICK_CENTER_Y_RATIO = 0.76;
  const ACTION_RADIUS_RATIO = 0.062;
  const ACTION_MARGIN_RATIO = 0.055;
  const ACTION_GAP_RATIO = 0.095;
  const HOTBAR_SLOT_RATIO = 0.11;
  const HOTBAR_GAP_RATIO = 0.015;
  const HOTBAR_BOTTOM_RATIO = 0.035;
  const LOOK_SENSITIVITY = 1.5;
  const MOVE_DEADZONE = 0.22;
  const HOTBAR_COUNT = 5;
  
  class Input {
    constructor(canvas, isWx = false) {
      this.canvas = canvas;
      this.isWx = isWx;
  
      this.mouseDX = 0;
      this.mouseDY = 0;
      this.pointerLocked = false;
  
      this.joystick = {
        active: false,
        baseX: 0,
        baseY: 0,
        stickX: 0,
        stickY: 0,
        radius: 60,
      };
  
      // 用于 HUD 高亮显示的按钮按下状态
      this.btns = {
        jump: false,
        attack: false,
        place: false,
      };
  
      // 单帧动作队列，按下时写入，update 时消费
      this._queued = {
        jump: false,
        attack: false,
        place: false,
        blockSelect: 0,
        toggleCamera: false,
      };
  
      this._keys = {};
      this._keyPressed = {};
      this._mouseLeft = false;
      this._mouseRight = false;
      this._mouseHUDAction = null;
  
      this._layout = null;
      this._joystickId = null;
      this._lookId = null;
      this._lastLookX = 0;
      this._lastLookY = 0;
      this._btnIds = {
        jump: null,
        attack: null,
        place: null,
      };
      this._hotbarTouchIds = new Set();
  
      if (isWx) {
        this._initWx();
      } else {
        this._initBrowser();
      }
    }
  
    resize() {
      this._layout = null;
    }
  
    getLayout() {
      if (!this._layout) this._layout = this._buildLayout();
      return this._layout;
    }
  
    // 兼容旧调用
    getBtnLayout() {
      return this.getLayout();
    }
  
    _getLogicalSize() {
      if (this.isWx) {
        const info = globalThis.wx.getSystemInfoSync();
        return { width: info.windowWidth, height: info.windowHeight };
      }
      const rect = this.canvas.getBoundingClientRect();
      return {
        width: rect.width > 0 ? rect.width : this.canvas.width,
        height: rect.height > 0 ? rect.height : this.canvas.height,
      };
    }
  
    _buildLayout() {
      const { width: W, height: H } = this._getLogicalSize();
      const S = Math.min(W, H);
  
      const joystickRadius = Math.round(S * JOYSTICK_RADIUS_RATIO);
      const joystickCenterX = Math.round(W * JOYSTICK_CENTER_X_RATIO);
      const joystickCenterY = Math.round(H * JOYSTICK_CENTER_Y_RATIO);
  
      const actionRadius = Math.round(S * ACTION_RADIUS_RATIO);
      const actionMargin = Math.round(S * ACTION_MARGIN_RATIO);
      const actionGap = Math.round(S * ACTION_GAP_RATIO * 1.2);
  
      const slotSize = Math.round(S * HOTBAR_SLOT_RATIO);
      const slotGap = Math.round(S * HOTBAR_GAP_RATIO);
      const hotbarWidth = HOTBAR_COUNT * slotSize + (HOTBAR_COUNT - 1) * slotGap;
      const hotbarX = Math.round((W - hotbarWidth) / 2);
      const hotbarY = Math.round(H - slotSize - S * HOTBAR_BOTTOM_RATIO);
  
      // 动作按钮布局：
      // - 跳：固定在右下角，最容易盲按
      // - 挖：在跳按钮左侧
      // - 放：在跳按钮上方
      // 同时适当拉大间距，避免三个按钮过于拥挤
      const jumpX = W - actionMargin - actionRadius;
      const jumpY = H - actionMargin - actionRadius;
      const attackX = jumpX - actionGap;
      const attackY = jumpY;
      const placeX = jumpX;
      const placeY = jumpY - actionGap;
  
      const hotbarSlots = [];
      for (let i = 0; i < HOTBAR_COUNT; i++) {
        hotbarSlots.push({
          index: i,
          x: hotbarX + i * (slotSize + slotGap),
          y: hotbarY,
          size: slotSize,
        });
      }
  
      const layout = {
        width: W,
        height: H,
        joystick: {
          x: joystickCenterX,
          y: joystickCenterY,
          radius: joystickRadius,
          hitRadius: joystickRadius * 1.75,
        },
        actions: {
          radius: actionRadius,
          jump: {
            x: jumpX,
            y: jumpY,
            label: '跳',
            color: '#44bb44',
          },
          attack: {
            x: attackX,
            y: attackY,
            label: '挖',
            color: '#cc4444',
          },
          place: {
            x: placeX,
            y: placeY,
            label: '放',
            color: '#4488dd',
          },
        },
        hotbar: {
          x: hotbarX,
          y: hotbarY,
          slotSize,
          slotGap,
          slots: hotbarSlots,
        },
      };
  
      this.joystick.radius = joystickRadius;
      return layout;
    }
  
    _toCanvas(clientX, clientY) {
      if (this.isWx) {
        return { x: clientX, y: clientY };
      }
      const rect = this.canvas.getBoundingClientRect();
      return {
        x: clientX - rect.left,
        y: clientY - rect.top,
      };
    }
  
    _hitActionButton(x, y) {
      const { actions } = this.getLayout();
      const names = ['jump', 'attack', 'place'];
      for (const name of names) {
        const btn = actions[name];
        const dx = x - btn.x;
        const dy = y - btn.y;
        if (dx * dx + dy * dy <= actions.radius * actions.radius) {
          return name;
        }
      }
      return null;
    }
  
    _hitHotbar(x, y) {
      const { hotbar } = this.getLayout();
      for (const slot of hotbar.slots) {
        if (
          x >= slot.x && x <= slot.x + slot.size &&
          y >= slot.y && y <= slot.y + slot.size
        ) {
          return slot.index;
        }
      }
      return -1;
    }
  
    _inJoystickZone(x, y) {
      const { joystick } = this.getLayout();
      const dx = x - joystick.x;
      const dy = y - joystick.y;
      return dx * dx + dy * dy <= joystick.hitRadius * joystick.hitRadius;
    }
  
    _beginJoystick(identifier) {
      const { joystick } = this.getLayout();
      this._joystickId = identifier;
      this.joystick.active = true;
      this.joystick.baseX = joystick.x;
      this.joystick.baseY = joystick.y;
      this.joystick.stickX = joystick.x;
      this.joystick.stickY = joystick.y;
    }
  
    _updateJoystick(x, y) {
      const bx = this.joystick.baseX;
      const by = this.joystick.baseY;
      const dx = x - bx;
      const dy = y - by;
      const len = Math.sqrt(dx * dx + dy * dy);
      const max = this.joystick.radius;
  
      if (len > max && len > 0.0001) {
        this.joystick.stickX = bx + dx / len * max;
        this.joystick.stickY = by + dy / len * max;
      } else {
        this.joystick.stickX = x;
        this.joystick.stickY = y;
      }
    }
  
    _queueAction(name) {
      this._queued[name] = true;
      this.btns[name] = true;
    }
  
    _releaseAction(name) {
      this.btns[name] = false;
    }
  
    _onTouchStart(touches) {
      const layout = this.getLayout();
  
      for (const touch of touches) {
        const { x, y } = this._toCanvas(touch.clientX, touch.clientY);
  
        const hotbarIndex = this._hitHotbar(x, y);
        if (hotbarIndex >= 0) {
          this._queued.blockSelect = hotbarIndex + 1;
          this._hotbarTouchIds.add(touch.identifier);
          continue;
        }
  
        const btn = this._hitActionButton(x, y);
        if (btn && this._btnIds[btn] === null) {
          this._btnIds[btn] = touch.identifier;
          this._queueAction(btn);
          continue;
        }
  
        if (x <= layout.width * 0.5 && this._joystickId === null) {
          this._beginJoystick(touch.identifier);
          this._updateJoystick(x, y);
          continue;
        }
  
        if (this._lookId === null) {
          this._lookId = touch.identifier;
          this._lastLookX = x;
          this._lastLookY = y;
        }
      }
    }
  
    _onTouchMove(touches) {
      for (const touch of touches) {
        const { x, y } = this._toCanvas(touch.clientX, touch.clientY);
  
        if (touch.identifier === this._joystickId) {
          this._updateJoystick(x, y);
          continue;
        }
  
        if (touch.identifier === this._lookId) {
          this.mouseDX += (x - this._lastLookX) * LOOK_SENSITIVITY;
          this.mouseDY += (y - this._lastLookY) * LOOK_SENSITIVITY;
          this._lastLookX = x;
          this._lastLookY = y;
        }
      }
    }
  
    _onTouchEnd(touches) {
      for (const touch of touches) {
        if (touch.identifier === this._joystickId) {
          this._joystickId = null;
          this.joystick.active = false;
          this.joystick.stickX = this.joystick.baseX;
          this.joystick.stickY = this.joystick.baseY;
        }
  
        if (touch.identifier === this._lookId) {
          this._lookId = null;
        }
  
        for (const name of ['jump', 'attack', 'place']) {
          if (touch.identifier === this._btnIds[name]) {
            this._btnIds[name] = null;
            this._releaseAction(name);
          }
        }
  
        this._hotbarTouchIds.delete(touch.identifier);
      }
    }
  
    _resetTouchState() {
      this._joystickId = null;
      this._lookId = null;
      this.joystick.active = false;
      this.joystick.stickX = this.joystick.baseX;
      this.joystick.stickY = this.joystick.baseY;
      for (const name of ['jump', 'attack', 'place']) {
        this._btnIds[name] = null;
        this._releaseAction(name);
      }
      this._hotbarTouchIds.clear();
    }
  
    _initBrowser() {
      const doc = globalThis.document;
      const win = globalThis.window;
      const canvas = this.canvas;
  
      doc.addEventListener('keydown', (e) => {
        this._keys[e.code] = true;
        if (!this._keyPressed[e.code]) this._keyPressed[e.code] = true;
        if (e.code === 'Escape' && this.pointerLocked) doc.exitPointerLock();
      });
  
      doc.addEventListener('keyup', (e) => {
        this._keys[e.code] = false;
        this._keyPressed[e.code] = false;
      });
  
      doc.addEventListener('pointerlockchange', () => {
        this.pointerLocked = doc.pointerLockElement === canvas;
      });
  
      doc.addEventListener('mousemove', (e) => {
        if (!this.pointerLocked) return;
        this.mouseDX += e.movementX;
        this.mouseDY += e.movementY;
      });
  
      canvas.addEventListener('mousedown', (e) => {
        if (this.pointerLocked) {
          if (e.button === 0) this._mouseLeft = true;
          if (e.button === 2) this._mouseRight = true;
          e.preventDefault();
          return;
        }
  
        const { x, y } = this._toCanvas(e.clientX, e.clientY);
        const hotbarIndex = this._hitHotbar(x, y);
        if (hotbarIndex >= 0) {
          this._queued.blockSelect = hotbarIndex + 1;
          e.preventDefault();
          return;
        }
  
        const btn = this._hitActionButton(x, y);
        if (btn) {
          this._mouseHUDAction = btn;
          this._queueAction(btn);
          e.preventDefault();
          return;
        }
  
        canvas.requestPointerLock();
      });
  
      canvas.addEventListener('mouseup', (e) => {
        if (this._mouseHUDAction) {
          this._releaseAction(this._mouseHUDAction);
          this._mouseHUDAction = null;
          e.preventDefault();
        }
        if (this.pointerLocked) {
          this._mouseLeft = false;
          this._mouseRight = false;
        }
      });
  
      canvas.addEventListener('contextmenu', (e) => e.preventDefault());
  
      const norm = (t) => ({ identifier: t.identifier, clientX: t.clientX, clientY: t.clientY });
      canvas.addEventListener('touchstart', (e) => {
        e.preventDefault();
        this._onTouchStart(Array.from(e.changedTouches).map(norm));
      }, { passive: false });
  
      // move/end/cancel 绑定到 document：
      // 手指拖出 canvas 边界后再松开时，canvas 自己不一定能收到 touchend，
      // 会导致摇杆 identifier 残留，角色持续移动。
      doc.addEventListener('touchmove', (e) => {
        if (!e.changedTouches || e.changedTouches.length === 0) return;
        e.preventDefault();
        this._onTouchMove(Array.from(e.changedTouches).map(norm));
      }, { passive: false });
      doc.addEventListener('touchend', (e) => {
        if (!e.changedTouches || e.changedTouches.length === 0) return;
        this._onTouchEnd(Array.from(e.changedTouches).map(norm));
      }, { passive: false });
      doc.addEventListener('touchcancel', (e) => {
        if (!e.changedTouches || e.changedTouches.length === 0) return;
        this._onTouchEnd(Array.from(e.changedTouches).map(norm));
      }, { passive: false });
  
      // 浏览器失焦、切标签或系统打断手势时，强制清空触摸状态，避免摇杆残留
      win.addEventListener('blur', () => this._resetTouchState());
      doc.addEventListener('visibilitychange', () => {
        if (doc.hidden) this._resetTouchState();
      });
    }
  
    _initWx() {
      const wx = globalThis.wx;
      const norm = (t) => ({ identifier: t.identifier, clientX: t.clientX, clientY: t.clientY });
      wx.onTouchStart((e) => this._onTouchStart(e.changedTouches.map(norm)));
      wx.onTouchMove((e) => this._onTouchMove(e.changedTouches.map(norm)));
      wx.onTouchEnd((e) => this._onTouchEnd(e.changedTouches.map(norm)));
      wx.onTouchCancel((e) => this._onTouchEnd(e.changedTouches.map(norm)));
    }
  
    update(player) {
      player.inputForward = false;
      player.inputBackward = false;
      player.inputLeft = false;
      player.inputRight = false;
      player.inputJump = false;
      player.clickLeft = false;
      player.clickRight = false;
      player.inputToggleCamera = false;
      player.blockSelectKey = 0;
  
      if (!this.isWx) this._applyKeyboard(player);
      this._applyTouch(player);
  
      player.onMouseMove(this.mouseDX, this.mouseDY);
      this.mouseDX = 0;
      this.mouseDY = 0;
    }
  
    _applyKeyboard(player) {
      const k = this._keys;
      const kp = this._keyPressed;
  
      player.inputForward = !!(k['KeyW'] || k['ArrowUp']);
      player.inputBackward = !!(k['KeyS'] || k['ArrowDown']);
      player.inputLeft = !!(k['KeyA'] || k['ArrowLeft']);
      player.inputRight = !!(k['KeyD'] || k['ArrowRight']);
      player.inputJump = !!k['Space'];
  
      if (this._mouseLeft) player.clickLeft = true;
      if (this._mouseRight) player.clickRight = true;
      this._mouseLeft = false;
      this._mouseRight = false;
  
      for (let i = 1; i <= HOTBAR_COUNT; i++) {
        if (kp[`Digit${i}`]) {
          player.blockSelectKey = i;
          kp[`Digit${i}`] = false;
        }
      }
  
      if (kp['KeyF']) {
        player.inputToggleCamera = true;
        kp['KeyF'] = false;
      }
    }
  
    _applyTouch(player) {
      const js = this.joystick;
      if (js.active) {
        const dx = (js.stickX - js.baseX) / js.radius;
        const dy = (js.stickY - js.baseY) / js.radius;
        if (dy < -MOVE_DEADZONE) player.inputForward = true;
        if (dy > MOVE_DEADZONE) player.inputBackward = true;
        if (dx < -MOVE_DEADZONE) player.inputLeft = true;
        if (dx > MOVE_DEADZONE) player.inputRight = true;
      }
  
      if (this._queued.jump) {
        player.inputJump = true;
        this._queued.jump = false;
      }
      if (this._queued.attack) {
        player.clickLeft = true;
        this._queued.attack = false;
      }
      if (this._queued.place) {
        player.clickRight = true;
        this._queued.place = false;
      }
      if (this._queued.toggleCamera) {
        player.inputToggleCamera = true;
        this._queued.toggleCamera = false;
      }
      if (this._queued.blockSelect > 0) {
        player.blockSelectKey = this._queued.blockSelect;
        this._queued.blockSelect = 0;
      }
    }
  }
  
  module.exports.Input = Input;;
  
  return module.exports;
})();

// Module: src\game.js
__modules[1] = (function() {
  const module = { exports: {} };
  /**
   * game.js - 游戏主类
   * 负责初始化各个子系统、管理游戏主循环
   * 支持浏览器和微信小游戏两种运行环境
   */
  
  const { Vec3, Mat4 } = __modules[2];
  const { World } = __modules[3];
  const { Renderer } = __modules[7];
  const { EntityRenderer } = __modules[9];
  const { Player, PLAYER_HEIGHT } = __modules[10];
  const { Input } = __modules[11];
  const { CHUNK_WIDTH, CHUNK_DEPTH } = __modules[4];
  const { Blocks } = __modules[5];
  
  class Game {
    /**
     * @param {object} options
     * @param {HTMLCanvasElement|object} options.canvas - 画布
     * @param {WebGLRenderingContext} options.gl - WebGL 上下文
   * @param {boolean} options.isWx - 是否微信小游戏
   * @param {object} options.hud - HUD 实例
   * @param {number} options.width - 画布宽
   * @param {number} options.height - 画布高
   */
    constructor({ canvas, gl, isWx = false, hud, width = 800, height = 600 }) {
      this.canvas = canvas;
      this.gl = gl;
      this.isWx = isWx;
      this.hud = hud;
  
      this.width = width;
      this.height = height;
      this.running = false;
      this.lastTime = 0;
      this._frameCount = 0;
      this._fpsTime = 0;
      this._fps = 60;
      this._firstFrame = true;
  
      // 当前放置的方块类型（可切换）
      this.selectedBlock = Blocks.GRASS;
      this._blockTypes = [Blocks.GRASS, Blocks.DIRT, Blocks.STONE, Blocks.WOOD, Blocks.LEAVES];
      this._blockTypeIndex = 0;
  
      // 初始化子系统
      this.world    = new World(42);
      this.renderer = new Renderer(gl, width, height);
      this.entityRenderer = new EntityRenderer(gl);
      this.player   = new Player(8, 40, 8);
      this.input    = new Input(canvas, isWx);
  
      // 实体列表（玩家也在其中，便于统一渲染）
      this.entities = [this.player];
  
      // 将玩家放到合适高度
      this._spawnPlayer();
  
      // FOV
      this.fov = 70 * Math.PI / 180;
      this.near = 0.1;
      this.far = 300;
    }
  
    /** 在出生点找到地面并放置玩家 */
    _spawnPlayer() {
      const x = 8;
      const z = 8;
      this.world.ensureChunksAround(x, z);
  
      // 螺旋扩展搜索第一个高于水面的陆地坐标
      let spawnX = x, spawnZ = z;
      outer:
      for (let r = 0; r <= 16; r++) {
        for (let dx = -r; dx <= r; dx++) {
          for (let dz = -r; dz <= r; dz++) {
            if (Math.abs(dx) !== r && Math.abs(dz) !== r) continue; // 只遍历当前环
            const h = this.world.getHeight(x + dx, z + dz);
            // getHeight 返回的 h 是固体地表顶面 Y
            // 当 h > 20（SEA_LEVEL）时地表在水面以上
            if (h > 20) {
              spawnX = x + dx;
              spawnZ = z + dz;
              break outer;
            }
          }
        }
      }
  
      const groundY = this.world.getHeight(spawnX, spawnZ);
      // 玩家脚底落在地表上方 1 格，再加上玩家身高偏移
      this.player.position.set(spawnX + 0.5, groundY + 1 + PLAYER_HEIGHT, spawnZ + 0.5);
    }
  
    /** 启动游戏主循环 */
    start() {
      this.running = true;
      this.lastTime = performance.now();
      this._loop();
    }
  
    /** 停止游戏 */
    stop() {
      this.running = false;
    }
  
    /** 主循环 */
    _loop() {
      if (!this.running) return;
  
      const now = performance.now();
      const dt = Math.min((now - this.lastTime) / 1000, 0.1); // 限制最大帧间隔
      this.lastTime = now;
  
      this._update(dt);
      this._render();
  
      // 下一帧（浏览器和微信小游戏都支持全局 requestAnimationFrame）
      requestAnimationFrame(() => this._loop());
    }
  
    /** 更新逻辑 */
    _update(dt) {
      // 输入
      this.input.update(this.player);
  
      // 单帧输入必须在 player.update 之前消费，因为 player.update 末尾会统一清零
      if (this.player.inputToggleCamera) {
        this.player.toggleCameraMode();
      }
  
      if (this.player.blockSelectKey > 0) {
        this._blockTypeIndex = this.player.blockSelectKey - 1;
        if (this._blockTypeIndex < this._blockTypes.length) {
          this.selectedBlock = this._blockTypes[this._blockTypeIndex];
        }
      }
  
      this._handleBlockInteraction();
  
      // 玩家物理
      this.player.update(dt, this.world);
  
      // 确保玩家周围的区块已加载
      this.world.ensureChunksAround(this.player.position.x, this.player.position.z);
  
  
      // 重建脏区块的网格
      const dirtyChunks = this.world.getDirtyChunks();
      const getWorldBlock = (wx, wy, wz) => this.world.getBlock(wx, wy, wz);
      for (const chunk of dirtyChunks) {
        const mesh = chunk.buildMesh(getWorldBlock);
        const key = `${chunk.cx},${chunk.cz}`;
        this.renderer.uploadChunkMesh(key, mesh);
      }
    }
  
    /** 处理方块放置/破坏 */
    _handleBlockInteraction() {
      if (!this.player.clickLeft && !this.player.clickRight) return;
  
      const hit = this.player.raycast(this.world);
      if (!hit) return;
  
      const [hx, hy, hz] = hit.hit;
      const [nx, ny, nz] = hit.normal;
  
      if (this.player.clickLeft) {
        // 左键破坏方块
        this.world.setBlock(hx, hy, hz, Blocks.AIR); // 0 = 空气
      } else if (this.player.clickRight) {
        // 右键放置方块（在命中的面法线方向）
        const px = hx + nx;
        const py = hy + ny;
        const pz = hz + nz;
        // 检查是否与玩家位置重叠
        const pPos = this.player.position;
        const feetY = Math.floor(pPos.y - PLAYER_HEIGHT);
        const headY = Math.floor(pPos.y);
        let overlapsPlayer = false;
        for (let y = Math.max(0, feetY); y <= headY; y++) {
          if (Math.floor(pPos.x) === px && y === py && Math.floor(pPos.z) === pz) {
            overlapsPlayer = true;
            break;
          }
        }
        if (!overlapsPlayer) {
          this.world.setBlock(px, py, pz, this.selectedBlock);
        }
      }
    }
  
    /** 渲染 */
    _render() {
      // getCameraInfo 根据视角模式返回正确的眼睛位置和视图矩阵
      const { eye, viewMatrix } = this.player.getCameraInfo(this.world);
      const aspect = this.width / this.height;
      const projMatrix = Mat4.perspective(this.fov, aspect, this.near, this.far);
      
      // 传入相机眼睛位置给渲染器，用于雾气计算
      this.renderer.render(viewMatrix, projMatrix, eye);
  
      // 第三人称时通过 EntityRenderer 渲染所有实体模型
      if (this.player.isThirdPerson()) {
        this.entityRenderer.drawEntities(
          this.entities,
          this.renderer._vpMatrix,
          this.renderer._cameraPos,
        );
      }
  
      // 更新 HUD 数据并绘制到离屏 Canvas
      this._updateHUD();
  
      // 将 HUD 离屏 Canvas 作为 WebGL 纹理覆盖到全屏（微信端与浏览器统一路径）
      this.renderer.drawHUD(this.hud.canvas);
  
    }
  
    /** 更新 HUD 显示 */
    _updateHUD() {
  
  
      // FPS 计算
      this._frameCount++;
      const now = performance.now();
      if (now - this._fpsTime >= 1000) {
        this._fps = this._frameCount;
        this._frameCount = 0;
        this._fpsTime = now;
      }
  
      // 首帧渲染后隐藏加载画面
      if (this._firstFrame) {
        this._firstFrame = false;
        this.hud.hideLoading();
      }
  
      const p = this.player.position;
      const cx = Math.floor(p.x / CHUNK_WIDTH);
      const cz = Math.floor(p.z / CHUNK_DEPTH);
  
      this.hud.update({
        pos: p,
        fps: this._fps,
        cx,
        cz,
        isThirdPerson: this.player.isThirdPerson(),
        blockIdx: this._blockTypeIndex,
      }, this.input); // 传入 input，供 HUD 绘制虚拟摇杆和按钮
    }
  
    /** 画布大小变更 */
    resize(width, height) {
      this.width = width;
      this.height = height;
      this.renderer.resize(width, height);
      this.input.resize();
      this.hud.resize(width, height);
    }
  }
  
  module.exports.Game = Game;;
  
  return module.exports;
})();

// Module: src\hud.js
__modules[12] = (function() {
  const module = { exports: {} };
  /**
   * hud.js - 统一 HUD（浏览器 + 微信小游戏）
   *
   * HUD 只负责在离屏 2D Canvas 上绘制，再由 renderer.drawHUD(hud.canvas)
   * 作为 WebGL 纹理叠加到最终画面。
   */
  
  const BLOCK_NAMES = ['草地', '泥土', '石头', '木头', '树叶'];
  
  class HUD {
    constructor(canvas, dpr = 1) {
      this.canvas = canvas;
      this._dpr = dpr || 1;
      this._ctx = canvas.getContext('2d');
  
      this.width = Math.round(canvas.width / this._dpr);
      this.height = Math.round(canvas.height / this._dpr);
  
      this._fontSize = Math.max(14, Math.round(this.width / 35));
      this._padding = this._fontSize * 0.7;
      this._lineH = this._fontSize * 1.6;
  
      this._loading = true;
      this._loadAlpha = 1.0;
      this._data = null;
      this._input = null;
  
      this._drawHUD();
    }
  
    resize(width, height) {
      this.canvas.width = width;
      this.canvas.height = height;
      this.width = Math.round(width / this._dpr);
      this.height = Math.round(height / this._dpr);
      this._fontSize = Math.max(14, Math.round(this.width / 35));
      this._padding = this._fontSize * 0.7;
      this._lineH = this._fontSize * 1.6;
    }
  
    hideLoading() {
      if (!this._loading) return;
      this._loading = false;
      this._loadAlpha = 1.0;
      this._fadeOutLoading();
    }
  
    update(data, input) {
      this._data = data;
      this._input = input;
      this._drawHUD();
    }
  
    _drawHUD() {
      const ctx = this._ctx;
  
      ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      ctx.save();
      ctx.scale(this._dpr, this._dpr);
  
      if (this._loading) {
        this._drawLoadingScreen(this._loadAlpha);
        ctx.restore();
        return;
      }
  
      if (!this._data) {
        ctx.restore();
        return;
      }
  
      this._drawInfoPanel(ctx);
      if (!this._data.isThirdPerson) this._drawCrosshair(ctx);
      this._drawHotbar(ctx);
  
      if (this._input) {
        this._drawJoystick(ctx);
        this._drawActions(ctx);
      }
  
      ctx.restore();
    }
  
    _drawInfoPanel(ctx) {
      const fs = this._fontSize;
      const pad = this._padding;
      const lh = this._lineH;
      const { pos, fps, cx, cz, isThirdPerson } = this._data;
  
      const lines = [
        `XYZ: ${pos.x.toFixed(1)}, ${pos.y.toFixed(1)}, ${pos.z.toFixed(1)}`,
        `FPS: ${fps}`,
        `区块: (${cx}, ${cz})`,
        `视角: ${isThirdPerson ? '第三人称' : '第一人称'}`,
      ];
  
      const width = fs * 15;
      const height = lines.length * lh + pad;
  
      ctx.fillStyle = 'rgba(0,0,0,0.5)';
      this._roundRect(ctx, pad, pad, width, height, 8);
      ctx.fill();
  
      ctx.font = `${fs}px monospace`;
      ctx.fillStyle = '#ffffff';
      ctx.textBaseline = 'top';
      ctx.textAlign = 'left';
      lines.forEach((line, index) => {
        ctx.fillText(line, pad * 2, pad + index * lh + pad * 0.35);
      });
    }
  
    _drawCrosshair(ctx) {
      const cx = this.width / 2;
      const cy = this.height / 2;
      const len = this._fontSize * 0.9;
  
      ctx.strokeStyle = 'rgba(255,255,255,0.92)';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(cx - len, cy);
      ctx.lineTo(cx + len, cy);
      ctx.moveTo(cx, cy - len);
      ctx.lineTo(cx, cy + len);
      ctx.stroke();
    }
  
    _drawHotbar(ctx) {
      const layout = this._input ? this._input.getLayout() : null;
      const slots = layout ? layout.hotbar.slots : this._buildFallbackHotbar();
      const selected = this._data.blockIdx;
  
      for (const slot of slots) {
        const isSelected = slot.index === selected;
        const x = slot.x;
        const y = slot.y;
        const size = slot.size;
  
        ctx.fillStyle = isSelected ? 'rgba(255,255,255,0.30)' : 'rgba(0,0,0,0.48)';
        this._roundRect(ctx, x, y, size, size, 6);
        ctx.fill();
  
        ctx.strokeStyle = isSelected ? '#ffffff' : 'rgba(255,255,255,0.35)';
        ctx.lineWidth = isSelected ? 2.5 : 1.2;
        this._roundRect(ctx, x, y, size, size, 6);
        ctx.stroke();
  
        ctx.font = `${Math.round(size * 0.24)}px monospace`;
        ctx.fillStyle = isSelected ? '#ffee88' : 'rgba(255,255,255,0.6)';
        ctx.textAlign = 'left';
        ctx.textBaseline = 'top';
        ctx.fillText(String(slot.index + 1), x + size * 0.08, y + size * 0.06);
  
        ctx.font = `bold ${Math.round(size * 0.22)}px sans-serif`;
        ctx.fillStyle = isSelected ? '#ffffff' : 'rgba(255,255,255,0.8)';
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.fillText(BLOCK_NAMES[slot.index], x + size / 2, y + size * 0.64);
      }
  
      ctx.textAlign = 'left';
    }
  
    _buildFallbackHotbar() {
      const size = Math.round(Math.min(this.width, this.height) * 0.11);
      const gap = Math.round(Math.min(this.width, this.height) * 0.015);
      const total = BLOCK_NAMES.length * size + (BLOCK_NAMES.length - 1) * gap;
      const x = Math.round((this.width - total) / 2);
      const y = Math.round(this.height - size - Math.min(this.width, this.height) * 0.035);
  
      return BLOCK_NAMES.map((_, index) => ({
        index,
        x: x + index * (size + gap),
        y,
        size,
      }));
    }
  
    _drawJoystick(ctx) {
      const { joystick } = this._input.getLayout();
      const state = this._input.joystick;
      const baseX = joystick.x;
      const baseY = joystick.y;
      const baseR = joystick.radius;
  
      ctx.beginPath();
      ctx.arc(baseX, baseY, baseR, 0, Math.PI * 2);
      ctx.fillStyle = 'rgba(255,255,255,0.12)';
      ctx.fill();
      ctx.strokeStyle = 'rgba(255,255,255,0.34)';
      ctx.lineWidth = 2;
      ctx.stroke();
  
      this._drawJoystickArrows(ctx, baseX, baseY, baseR);
  
      const knobX = state.active ? state.stickX : baseX;
      const knobY = state.active ? state.stickY : baseY;
      const knobR = baseR * 0.46;
  
      ctx.beginPath();
      ctx.arc(knobX, knobY, knobR, 0, Math.PI * 2);
      ctx.fillStyle = state.active ? 'rgba(255,255,255,0.55)' : 'rgba(255,255,255,0.26)';
      ctx.fill();
      ctx.strokeStyle = 'rgba(255,255,255,0.60)';
      ctx.lineWidth = 2;
      ctx.stroke();
    }
  
    _drawJoystickArrows(ctx, cx, cy, r) {
      const size = r * 0.2;
      const dist = r * 0.7;
      const dirs = [
        [0, -dist, 0],
        [0, dist, Math.PI],
        [-dist, 0, -Math.PI / 2],
        [dist, 0, Math.PI / 2],
      ];
  
      ctx.fillStyle = 'rgba(255,255,255,0.42)';
      for (const [dx, dy, angle] of dirs) {
        ctx.save();
        ctx.translate(cx + dx, cy + dy);
        ctx.rotate(angle);
        ctx.beginPath();
        ctx.moveTo(0, -size);
        ctx.lineTo(size * 0.72, size * 0.55);
        ctx.lineTo(-size * 0.72, size * 0.55);
        ctx.closePath();
        ctx.fill();
        ctx.restore();
      }
    }
  
    _drawActions(ctx) {
      const { actions } = this._input.getLayout();
      this._drawActionButton(ctx, actions.jump, this._input.btns.jump);
      this._drawActionButton(ctx, actions.attack, this._input.btns.attack);
      this._drawActionButton(ctx, actions.place, this._input.btns.place);
    }
  
    _drawActionButton(ctx, btn, pressed) {
      const radius = this._input.getLayout().actions.radius;
  
      ctx.beginPath();
      ctx.arc(btn.x, btn.y, radius, 0, Math.PI * 2);
      ctx.fillStyle = this._colorWithAlpha(btn.color, pressed ? 0.78 : 0.38);
      ctx.fill();
      ctx.strokeStyle = pressed ? 'rgba(255,255,255,0.95)' : 'rgba(255,255,255,0.5)';
      ctx.lineWidth = pressed ? 2.8 : 1.5;
      ctx.stroke();
  
      ctx.font = `bold ${Math.round(radius * 0.52)}px sans-serif`;
      ctx.fillStyle = '#ffffff';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(btn.label, btn.x, btn.y);
      ctx.textAlign = 'left';
    }
  
    _colorWithAlpha(hex, alpha) {
      let h = hex.replace('#', '');
      if (h.length === 3) h = h.split('').map((c) => c + c).join('');
      const n = parseInt(h, 16);
      return `rgba(${(n >> 16) & 255},${(n >> 8) & 255},${n & 255},${alpha})`;
    }
  
    _drawLoadingScreen(alpha) {
      const ctx = this._ctx;
      const w = this.width;
      const h = this.height;
      const fs = this._fontSize * 1.6;
  
      ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      ctx.globalAlpha = alpha;
      ctx.fillStyle = 'rgb(20, 48, 20)';
      ctx.fillRect(0, 0, w, h);
  
      ctx.font = `bold ${fs * 1.5}px sans-serif`;
      ctx.fillStyle = '#7ec850';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText('我的世界', w / 2, h / 2 - fs * 0.7);
  
      ctx.font = `${fs * 0.85}px sans-serif`;
      ctx.fillStyle = '#aaaaaa';
      ctx.fillText('世界生成中...', w / 2, h / 2 + fs * 0.6);
  
      ctx.globalAlpha = 1;
      ctx.textAlign = 'left';
    }
  
    _fadeOutLoading() {
      const step = () => {
        this._loadAlpha -= 0.06;
        if (this._loadAlpha <= 0) {
          this._loadAlpha = 0;
          this._drawHUD();
          return;
        }
        this._drawHUD();
        requestAnimationFrame(step);
      };
      requestAnimationFrame(step);
    }
  
    _roundRect(ctx, x, y, w, h, r) {
      ctx.beginPath();
      ctx.moveTo(x + r, y);
      ctx.lineTo(x + w - r, y);
      ctx.arcTo(x + w, y, x + w, y + r, r);
      ctx.lineTo(x + w, y + h - r);
      ctx.arcTo(x + w, y + h, x + w - r, y + h, r);
      ctx.lineTo(x + r, y + h);
      ctx.arcTo(x, y + h, x, y + h - r, r);
      ctx.lineTo(x, y + r);
      ctx.arcTo(x, y, x + r, y, r);
      ctx.closePath();
    }
  }
  
  module.exports.HUD = HUD;;
  
  return module.exports;
})();

// Module: src\main.js
__modules[0] = (function() {
  const module = { exports: {} };
  /**
   * main.js - 入口文件
   * 检测运行环境，自动适配浏览器或微信小游戏
   */
  
  const { Game } = __modules[1];
  const { HUD } = __modules[12];
  
  // ===================== 浏览器环境 =====================
  
  function initBrowser() {
    const document = globalThis.document;
    const window   = globalThis.window;
    const canvas = document.getElementById('gameCanvas');
    if (!canvas) {
      console.error('找不到 #gameCanvas');
      return;
    }
  
    // 全屏适配：统一使用 CSS 逻辑像素，触摸坐标和布局坐标天然一致，无需 DPR 换算
    function resize() {
      canvas.width  = window.innerWidth;
      canvas.height = window.innerHeight;
      canvas.style.width  = canvas.width  + 'px';
      canvas.style.height = canvas.height + 'px';
      if (window._game) {
        window._game.resize(canvas.width, canvas.height);
      }
    }
    window.addEventListener('resize', resize);
    resize();
  
    // 获取 WebGL 上下文
    const gl = canvas.getContext('webgl', {
      antialias: false,
      alpha: false,
      depth: true,
      stencil: false,
      premultipliedAlpha: false,
    });
  
    if (!gl) {
      document.body.innerHTML = '<h1 style="color:white;text-align:center;margin-top:40vh">您的浏览器不支持 WebGL</h1>';
      return;
    }
  
    // 启用 Uint32 索引支持
    const ext = gl.getExtension('OES_element_index_uint');
    if (!ext) {
      console.warn('OES_element_index_uint 不可用，大区块可能无法渲染');
    }
  
    // 浏览器端主画布本身就使用逻辑像素，HUD 也按同一坐标系绘制即可
    const hudCanvas = globalThis.document.createElement('canvas');
    hudCanvas.width  = canvas.width;
    hudCanvas.height = canvas.height;
    const hud = new HUD(hudCanvas, 1);
  
    // 创建并启动游戏
    const game = new Game({
      canvas,
      gl,
      isWx: false,
      hud,
      width: canvas.width,
      height: canvas.height,
    });
  
    window._game = game;
    game.start();
  }
  
  // ===================== 微信小游戏环境 =====================
  
  function initWx() {
    const wx = globalThis.wx;
  
    // 主 WebGL 画布（第一次 createCanvas）
    const canvas = wx.createCanvas();
    const gl = canvas.getContext('webgl', {
      antialias: false,
      alpha: false,
      depth: true,
    });
  
    if (!gl) {
      console.error('微信小游戏 WebGL 初始化失败');
      return;
    }
  
    gl.getExtension('OES_element_index_uint');
  
    const info = wx.getSystemInfoSync();
    const pw = info.windowWidth  * (info.pixelRatio || 1);
    const ph = info.windowHeight * (info.pixelRatio || 1);
  
    canvas.width  = pw;
    canvas.height = ph;
  
    // 统一 HUD：微信第二次 createCanvas() 返回离屏 2D 画布，直接传入
    const dpr = info.pixelRatio || 1;
    const hudCanvas = wx.createCanvas();
    hudCanvas.width  = pw;
    hudCanvas.height = ph;
    const hud = new HUD(hudCanvas, dpr);
  
    const game = new Game({
      canvas,
      gl,
      isWx: true,
      hud,
      width: pw,
      height: ph,
    });
  
    game.start();
  }
  
  // ===================== 自动检测环境 =====================
  
  if (globalThis.wx && globalThis.wx.createCanvas) {
    initWx();
  } else if (typeof document !== 'undefined') {
    // 等待 DOM 加载完成
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', initBrowser);
    } else {
      initBrowser();
    }
  }
  
  return module.exports;
})();

// Execute entry
__modules[0];
