/**
 * build.js - 构建脚本
 * 将 src/ 下所有 ES module 文件打包为微信小游戏可用的单文件
 * 使用方式: node build.js
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const WX_DIR = path.join(__dirname, 'wx');

// 模块依赖图
const moduleMap = new Map();
let moduleIndex = 0;

/** 递归解析模块依赖 */
function parseModule(filePath) {
  if (moduleMap.has(filePath)) return moduleMap.get(filePath).id;

  const code = fs.readFileSync(filePath, 'utf-8');
  const id = moduleIndex++;
  const deps = [];

  // 匹配 import ... from '...' 语句
  const importRegex = /import\s+(?:\{[^}]*\}|\*\s+as\s+\w+)\s+from\s+['"]\.\/([^'"]+)['"]/g;
  let match;
  while ((match = importRegex.exec(code)) !== null) {
    const depMod = match[1].endsWith('.js') ? match[1] : match[1] + '.js';
    const depPath = path.resolve(path.dirname(filePath), depMod);
    deps.push(depPath);
  }

  moduleMap.set(filePath, { id, code, deps, filePath });

  // 递归解析依赖
  for (const dep of deps) {
    parseModule(dep);
  }

  return id;
}

/** 转换 ES module 语法为 CommonJS */
function transformModule(filePath) {
  const mod = moduleMap.get(filePath);
  let code = mod.code;

  // 替换 export { ... } 为 module.exports = { ... }
  code = code.replace(/export\s*\{([^}]*)\}/, (match, exports) => {
    const items = exports.split(',').map(s => s.trim()).filter(Boolean);
    return 'module.exports = {\n  ' + items.join(',\n  ') + '\n};';
  });

  // 替换 import { ... } from './xxx' 为 const { ... } = require()
  code = code.replace(/import\s*\{([^}]*)\}\s*from\s*['"]\.\/([^'"]+)['"]/g, (match, imports, modPath) => {
    const depMod = modPath.endsWith('.js') ? modPath : modPath + '.js';
    const depPath = path.resolve(path.dirname(filePath), depMod);
    const depId = moduleMap.get(depPath).id;
    const items = imports.split(',').map(s => s.trim()).filter(Boolean);
    return `const { ${items.join(', ')} } = __modules[${depId}]`;
  });

  return code;
}

/** 主构建流程 */
function build() {
  console.log('🔨 开始构建微信小游戏版本...');

  // 从入口开始解析
  const entryFile = path.join(SRC_DIR, 'main.js');
  parseModule(entryFile);

  // 拓扑排序
  const sorted = [];
  const visited = new Set();
  function visit(filePath) {
    if (visited.has(filePath)) return;
    visited.add(filePath);
    const mod = moduleMap.get(filePath);
    for (const dep of mod.deps) {
      visit(dep);
    }
    sorted.push(filePath);
  }
  visit(entryFile);

  // 生成打包代码
  let output = '// Auto-generated by build.js\n';
  output += '// 微信小游戏版本 - 打包时间: ' + new Date().toISOString() + '\n\n';
  output += 'const __modules = {};\n\n';

  for (const filePath of sorted) {
    const mod = moduleMap.get(filePath);
    const transformed = transformModule(filePath);
    output += `// Module: ${path.relative(__dirname, filePath)}\n`;
    output += `__modules[${mod.id}] = (function() {\n`;
    output += `  const module = { exports: {} };\n`;
    output += `  ${transformed.replace(/\n/g, '\n  ')}\n`;
    output += `  return module.exports;\n`;
    output += `})();\n\n`;
  }

  // 入口执行
  const entryId = moduleMap.get(entryFile).id;
  output += `// Execute entry\n__modules[${entryId}];\n`;

  // 写入
  const wxGameJs = path.join(WX_DIR, 'game.js');
  fs.writeFileSync(wxGameJs, output, 'utf-8');

  console.log(`✅ 构建完成! 输出: ${wxGameJs}`);
  console.log(`   模块数: ${sorted.length}`);
}

// 复制微信小游戏所需文件
function copyWxFiles() {
  const gameJson = {
    deviceOrientation: 'landscape',
    showStatusBar: false,
    networkTimeout: {
      request: 5000,
      connectSocket: 5000,
      uploadFile: 5000,
      downloadFile: 5000
    }
  };

  fs.writeFileSync(
    path.join(WX_DIR, 'game.json'),
    JSON.stringify(gameJson, null, 2),
    'utf-8'
  );
  console.log('✅ game.json 已生成');
}

// 执行
build();
copyWxFiles();
